/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model;


import com.treetory.dsltest.model.tables.Checkaccessrights;
import com.treetory.dsltest.model.tables.Dologin;
import com.treetory.dsltest.model.tables.Getbarpatientlist;
import com.treetory.dsltest.model.tables.Getcodetailhistorylist;
import com.treetory.dsltest.model.tables.Getcollaborationdetail;
import com.treetory.dsltest.model.tables.Getcopatientlist;
import com.treetory.dsltest.model.tables.Getdeptlist;
import com.treetory.dsltest.model.tables.Getdoctorinfo;
import com.treetory.dsltest.model.tables.Getdoctorlistbydept;
import com.treetory.dsltest.model.tables.Getdrugdetail;
import com.treetory.dsltest.model.tables.Getdruginfo;
import com.treetory.dsltest.model.tables.Getempatientlist;
import com.treetory.dsltest.model.tables.Getemtreatstatlist;
import com.treetory.dsltest.model.tables.Getexamlist;
import com.treetory.dsltest.model.tables.Getexamreceiptdeptlist;
import com.treetory.dsltest.model.tables.Getexamrsltty1;
import com.treetory.dsltest.model.tables.Getexamrsltty2;
import com.treetory.dsltest.model.tables.Getindatelist;
import com.treetory.dsltest.model.tables.Getinhistorylist;
import com.treetory.dsltest.model.tables.Getinpatientlist;
import com.treetory.dsltest.model.tables.Getmedicationlist;
import com.treetory.dsltest.model.tables.Getmedirecord;
import com.treetory.dsltest.model.tables.Getmedirecordcontentdetail;
import com.treetory.dsltest.model.tables.Getmedirecorddetail;
import com.treetory.dsltest.model.tables.Getmedirecordformlist;
import com.treetory.dsltest.model.tables.Getmedirecordlist;
import com.treetory.dsltest.model.tables.Getnfcpatientlist;
import com.treetory.dsltest.model.tables.Getondutymonthsch;
import com.treetory.dsltest.model.tables.Getondutyweeksch;
import com.treetory.dsltest.model.tables.Getopdetailhistorylist;
import com.treetory.dsltest.model.tables.Getoperationcntrlist;
import com.treetory.dsltest.model.tables.Getoperationdetail;
import com.treetory.dsltest.model.tables.Getoperationroomlist;
import com.treetory.dsltest.model.tables.Getoperationstatlist;
import com.treetory.dsltest.model.tables.Getophistorylist;
import com.treetory.dsltest.model.tables.Getoppatientlist;
import com.treetory.dsltest.model.tables.Getoutdatelist;
import com.treetory.dsltest.model.tables.Getouthistorylist;
import com.treetory.dsltest.model.tables.Getoutpatientlist;
import com.treetory.dsltest.model.tables.Getouttreatstatlist;
import com.treetory.dsltest.model.tables.Getpatientinfo;
import com.treetory.dsltest.model.tables.Getpatientnotice;
import com.treetory.dsltest.model.tables.Getprescription;
import com.treetory.dsltest.model.tables.Getprescriptionclslist;
import com.treetory.dsltest.model.tables.Getprescriptionstatlist;
import com.treetory.dsltest.model.tables.Getqrpatientlist;
import com.treetory.dsltest.model.tables.Getroomlistbyward;
import com.treetory.dsltest.model.tables.Getschexamdeptlist;
import com.treetory.dsltest.model.tables.Getshcdeptlist;
import com.treetory.dsltest.model.tables.Getshcwardlist;
import com.treetory.dsltest.model.tables.Gettrdetailhistorylist;
import com.treetory.dsltest.model.tables.Gettreatmentcntrlist;
import com.treetory.dsltest.model.tables.Gettreatmentdetail;
import com.treetory.dsltest.model.tables.Gettreatmentstatlist;
import com.treetory.dsltest.model.tables.Gettrpatientlist;
import com.treetory.dsltest.model.tables.Getvitallist;
import com.treetory.dsltest.model.tables.Getvitallistsum2;
import com.treetory.dsltest.model.tables.Getwardlist;
import com.treetory.dsltest.model.tables.Getworksch;
import com.treetory.dsltest.model.tables.Getwoundimg;
import com.treetory.dsltest.model.tables.Inputdownloadlog;
import com.treetory.dsltest.model.tables.Inputloginlog;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mplus_test_data
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mplus_test_data.checkaccessrights</code>.
     */
    public static final Checkaccessrights CHECKACCESSRIGHTS = com.treetory.dsltest.model.tables.Checkaccessrights.CHECKACCESSRIGHTS;

    /**
     * The table <code>mplus_test_data.dologin</code>.
     */
    public static final Dologin DOLOGIN = com.treetory.dsltest.model.tables.Dologin.DOLOGIN;

    /**
     * The table <code>mplus_test_data.getbarpatientlist</code>.
     */
    public static final Getbarpatientlist GETBARPATIENTLIST = com.treetory.dsltest.model.tables.Getbarpatientlist.GETBARPATIENTLIST;

    /**
     * 협진 이력 목록 조회
     */
    public static final Getcodetailhistorylist GETCODETAILHISTORYLIST = com.treetory.dsltest.model.tables.Getcodetailhistorylist.GETCODETAILHISTORYLIST;

    /**
     * The table <code>mplus_test_data.getcollaborationdetail</code>.
     */
    public static final Getcollaborationdetail GETCOLLABORATIONDETAIL = com.treetory.dsltest.model.tables.Getcollaborationdetail.GETCOLLABORATIONDETAIL;

    /**
     * The table <code>mplus_test_data.getcopatientlist</code>.
     */
    public static final Getcopatientlist GETCOPATIENTLIST = com.treetory.dsltest.model.tables.Getcopatientlist.GETCOPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getdeptlist</code>.
     */
    public static final Getdeptlist GETDEPTLIST = com.treetory.dsltest.model.tables.Getdeptlist.GETDEPTLIST;

    /**
     * The table <code>mplus_test_data.getdoctorinfo</code>.
     */
    public static final Getdoctorinfo GETDOCTORINFO = com.treetory.dsltest.model.tables.Getdoctorinfo.GETDOCTORINFO;

    /**
     * The table <code>mplus_test_data.getdoctorlistbydept</code>.
     */
    public static final Getdoctorlistbydept GETDOCTORLISTBYDEPT = com.treetory.dsltest.model.tables.Getdoctorlistbydept.GETDOCTORLISTBYDEPT;

    /**
     * 복약지도전문
     */
    public static final Getdrugdetail GETDRUGDETAIL = com.treetory.dsltest.model.tables.Getdrugdetail.GETDRUGDETAIL;

    /**
     * The table <code>mplus_test_data.getdruginfo</code>.
     */
    public static final Getdruginfo GETDRUGINFO = com.treetory.dsltest.model.tables.Getdruginfo.GETDRUGINFO;

    /**
     * The table <code>mplus_test_data.getempatientlist</code>.
     */
    public static final Getempatientlist GETEMPATIENTLIST = com.treetory.dsltest.model.tables.Getempatientlist.GETEMPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getemtreatstatlist</code>.
     */
    public static final Getemtreatstatlist GETEMTREATSTATLIST = com.treetory.dsltest.model.tables.Getemtreatstatlist.GETEMTREATSTATLIST;

    /**
     * The table <code>mplus_test_data.getexamlist</code>.
     */
    public static final Getexamlist GETEXAMLIST = com.treetory.dsltest.model.tables.Getexamlist.GETEXAMLIST;

    /**
     * The table <code>mplus_test_data.getexamreceiptdeptlist</code>.
     */
    public static final Getexamreceiptdeptlist GETEXAMRECEIPTDEPTLIST = com.treetory.dsltest.model.tables.Getexamreceiptdeptlist.GETEXAMRECEIPTDEPTLIST;

    /**
     * The table <code>mplus_test_data.getexamrsltty1</code>.
     */
    public static final Getexamrsltty1 GETEXAMRSLTTY1 = com.treetory.dsltest.model.tables.Getexamrsltty1.GETEXAMRSLTTY1;

    /**
     * The table <code>mplus_test_data.getexamrsltty2</code>.
     */
    public static final Getexamrsltty2 GETEXAMRSLTTY2 = com.treetory.dsltest.model.tables.Getexamrsltty2.GETEXAMRSLTTY2;

    /**
     * The table <code>mplus_test_data.getindatelist</code>.
     */
    public static final Getindatelist GETINDATELIST = com.treetory.dsltest.model.tables.Getindatelist.GETINDATELIST;

    /**
     * The table <code>mplus_test_data.getinhistorylist</code>.
     */
    public static final Getinhistorylist GETINHISTORYLIST = com.treetory.dsltest.model.tables.Getinhistorylist.GETINHISTORYLIST;

    /**
     * The table <code>mplus_test_data.getinpatientlist</code>.
     */
    public static final Getinpatientlist GETINPATIENTLIST = com.treetory.dsltest.model.tables.Getinpatientlist.GETINPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getmedicationlist</code>.
     */
    public static final Getmedicationlist GETMEDICATIONLIST = com.treetory.dsltest.model.tables.Getmedicationlist.GETMEDICATIONLIST;

    /**
     * The table <code>mplus_test_data.getmedirecord</code>.
     */
    public static final Getmedirecord GETMEDIRECORD = com.treetory.dsltest.model.tables.Getmedirecord.GETMEDIRECORD;

    /**
     * The table <code>mplus_test_data.getmedirecordcontentdetail</code>.
     */
    public static final Getmedirecordcontentdetail GETMEDIRECORDCONTENTDETAIL = com.treetory.dsltest.model.tables.Getmedirecordcontentdetail.GETMEDIRECORDCONTENTDETAIL;

    /**
     * The table <code>mplus_test_data.getmedirecorddetail</code>.
     */
    public static final Getmedirecorddetail GETMEDIRECORDDETAIL = com.treetory.dsltest.model.tables.Getmedirecorddetail.GETMEDIRECORDDETAIL;

    /**
     * The table <code>mplus_test_data.getmedirecordformlist</code>.
     */
    public static final Getmedirecordformlist GETMEDIRECORDFORMLIST = com.treetory.dsltest.model.tables.Getmedirecordformlist.GETMEDIRECORDFORMLIST;

    /**
     * The table <code>mplus_test_data.getmedirecordlist</code>.
     */
    public static final Getmedirecordlist GETMEDIRECORDLIST = com.treetory.dsltest.model.tables.Getmedirecordlist.GETMEDIRECORDLIST;

    /**
     * The table <code>mplus_test_data.getnfcpatientlist</code>.
     */
    public static final Getnfcpatientlist GETNFCPATIENTLIST = com.treetory.dsltest.model.tables.Getnfcpatientlist.GETNFCPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getondutymonthsch</code>.
     */
    public static final Getondutymonthsch GETONDUTYMONTHSCH = com.treetory.dsltest.model.tables.Getondutymonthsch.GETONDUTYMONTHSCH;

    /**
     * The table <code>mplus_test_data.getondutyweeksch</code>.
     */
    public static final Getondutyweeksch GETONDUTYWEEKSCH = com.treetory.dsltest.model.tables.Getondutyweeksch.GETONDUTYWEEKSCH;

    /**
     * 수술 이력 목록 조회
     */
    public static final Getopdetailhistorylist GETOPDETAILHISTORYLIST = com.treetory.dsltest.model.tables.Getopdetailhistorylist.GETOPDETAILHISTORYLIST;

    /**
     * The table <code>mplus_test_data.getoperationcntrlist</code>.
     */
    public static final Getoperationcntrlist GETOPERATIONCNTRLIST = com.treetory.dsltest.model.tables.Getoperationcntrlist.GETOPERATIONCNTRLIST;

    /**
     * The table <code>mplus_test_data.getoperationdetail</code>.
     */
    public static final Getoperationdetail GETOPERATIONDETAIL = com.treetory.dsltest.model.tables.Getoperationdetail.GETOPERATIONDETAIL;

    /**
     * The table <code>mplus_test_data.getoperationroomlist</code>.
     */
    public static final Getoperationroomlist GETOPERATIONROOMLIST = com.treetory.dsltest.model.tables.Getoperationroomlist.GETOPERATIONROOMLIST;

    /**
     * The table <code>mplus_test_data.getoperationstatlist</code>.
     */
    public static final Getoperationstatlist GETOPERATIONSTATLIST = com.treetory.dsltest.model.tables.Getoperationstatlist.GETOPERATIONSTATLIST;

    /**
     * The table <code>mplus_test_data.getophistorylist</code>.
     */
    public static final Getophistorylist GETOPHISTORYLIST = com.treetory.dsltest.model.tables.Getophistorylist.GETOPHISTORYLIST;

    /**
     * The table <code>mplus_test_data.getoppatientlist</code>.
     */
    public static final Getoppatientlist GETOPPATIENTLIST = com.treetory.dsltest.model.tables.Getoppatientlist.GETOPPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getoutdatelist</code>.
     */
    public static final Getoutdatelist GETOUTDATELIST = com.treetory.dsltest.model.tables.Getoutdatelist.GETOUTDATELIST;

    /**
     * The table <code>mplus_test_data.getouthistorylist</code>.
     */
    public static final Getouthistorylist GETOUTHISTORYLIST = com.treetory.dsltest.model.tables.Getouthistorylist.GETOUTHISTORYLIST;

    /**
     * The table <code>mplus_test_data.getoutpatientlist</code>.
     */
    public static final Getoutpatientlist GETOUTPATIENTLIST = com.treetory.dsltest.model.tables.Getoutpatientlist.GETOUTPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getouttreatstatlist</code>.
     */
    public static final Getouttreatstatlist GETOUTTREATSTATLIST = com.treetory.dsltest.model.tables.Getouttreatstatlist.GETOUTTREATSTATLIST;

    /**
     * The table <code>mplus_test_data.getpatientinfo</code>.
     */
    public static final Getpatientinfo GETPATIENTINFO = com.treetory.dsltest.model.tables.Getpatientinfo.GETPATIENTINFO;

    /**
     * The table <code>mplus_test_data.getpatientnotice</code>.
     */
    public static final Getpatientnotice GETPATIENTNOTICE = com.treetory.dsltest.model.tables.Getpatientnotice.GETPATIENTNOTICE;

    /**
     * The table <code>mplus_test_data.getprescription</code>.
     */
    public static final Getprescription GETPRESCRIPTION = com.treetory.dsltest.model.tables.Getprescription.GETPRESCRIPTION;

    /**
     * The table <code>mplus_test_data.getprescriptionclslist</code>.
     */
    public static final Getprescriptionclslist GETPRESCRIPTIONCLSLIST = com.treetory.dsltest.model.tables.Getprescriptionclslist.GETPRESCRIPTIONCLSLIST;

    /**
     * The table <code>mplus_test_data.getprescriptionstatlist</code>.
     */
    public static final Getprescriptionstatlist GETPRESCRIPTIONSTATLIST = com.treetory.dsltest.model.tables.Getprescriptionstatlist.GETPRESCRIPTIONSTATLIST;

    /**
     * The table <code>mplus_test_data.getqrpatientlist</code>.
     */
    public static final Getqrpatientlist GETQRPATIENTLIST = com.treetory.dsltest.model.tables.Getqrpatientlist.GETQRPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getroomlistbyward</code>.
     */
    public static final Getroomlistbyward GETROOMLISTBYWARD = com.treetory.dsltest.model.tables.Getroomlistbyward.GETROOMLISTBYWARD;

    /**
     * The table <code>mplus_test_data.getschexamdeptlist</code>.
     */
    public static final Getschexamdeptlist GETSCHEXAMDEPTLIST = com.treetory.dsltest.model.tables.Getschexamdeptlist.GETSCHEXAMDEPTLIST;

    /**
     * The table <code>mplus_test_data.getshcdeptlist</code>.
     */
    public static final Getshcdeptlist GETSHCDEPTLIST = com.treetory.dsltest.model.tables.Getshcdeptlist.GETSHCDEPTLIST;

    /**
     * The table <code>mplus_test_data.getshcwardlist</code>.
     */
    public static final Getshcwardlist GETSHCWARDLIST = com.treetory.dsltest.model.tables.Getshcwardlist.GETSHCWARDLIST;

    /**
     * 시술 이력 목록 조회
     */
    public static final Gettrdetailhistorylist GETTRDETAILHISTORYLIST = com.treetory.dsltest.model.tables.Gettrdetailhistorylist.GETTRDETAILHISTORYLIST;

    /**
     * The table <code>mplus_test_data.gettreatmentcntrlist</code>.
     */
    public static final Gettreatmentcntrlist GETTREATMENTCNTRLIST = com.treetory.dsltest.model.tables.Gettreatmentcntrlist.GETTREATMENTCNTRLIST;

    /**
     * The table <code>mplus_test_data.gettreatmentdetail</code>.
     */
    public static final Gettreatmentdetail GETTREATMENTDETAIL = com.treetory.dsltest.model.tables.Gettreatmentdetail.GETTREATMENTDETAIL;

    /**
     * The table <code>mplus_test_data.gettreatmentstatlist</code>.
     */
    public static final Gettreatmentstatlist GETTREATMENTSTATLIST = com.treetory.dsltest.model.tables.Gettreatmentstatlist.GETTREATMENTSTATLIST;

    /**
     * The table <code>mplus_test_data.gettrpatientlist</code>.
     */
    public static final Gettrpatientlist GETTRPATIENTLIST = com.treetory.dsltest.model.tables.Gettrpatientlist.GETTRPATIENTLIST;

    /**
     * The table <code>mplus_test_data.getvitallist</code>.
     */
    public static final Getvitallist GETVITALLIST = com.treetory.dsltest.model.tables.Getvitallist.GETVITALLIST;

    /**
     * The table <code>mplus_test_data.getvitallistsum2</code>.
     */
    public static final Getvitallistsum2 GETVITALLISTSUM2 = com.treetory.dsltest.model.tables.Getvitallistsum2.GETVITALLISTSUM2;

    /**
     * The table <code>mplus_test_data.getwardlist</code>.
     */
    public static final Getwardlist GETWARDLIST = com.treetory.dsltest.model.tables.Getwardlist.GETWARDLIST;

    /**
     * The table <code>mplus_test_data.getworksch</code>.
     */
    public static final Getworksch GETWORKSCH = com.treetory.dsltest.model.tables.Getworksch.GETWORKSCH;

    /**
     * The table <code>mplus_test_data.getwoundimg</code>.
     */
    public static final Getwoundimg GETWOUNDIMG = com.treetory.dsltest.model.tables.Getwoundimg.GETWOUNDIMG;

    /**
     * The table <code>mplus_test_data.inputdownloadlog</code>.
     */
    public static final Inputdownloadlog INPUTDOWNLOADLOG = com.treetory.dsltest.model.tables.Inputdownloadlog.INPUTDOWNLOADLOG;

    /**
     * The table <code>mplus_test_data.inputloginlog</code>.
     */
    public static final Inputloginlog INPUTLOGINLOG = com.treetory.dsltest.model.tables.Inputloginlog.INPUTLOGINLOG;
}
