/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Dologin;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DologinRecord extends TableRecordImpl<DologinRecord> implements Record12<String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 943478083;

    /**
     * Setter for <code>mplus_test_data.dologin.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.userId</code>.
     */
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.userId</code>.
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.userNm</code>.
     */
    public void setUsernm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.userNm</code>.
     */
    public String getUsernm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.jobKindCd</code>.
     */
    public void setJobkindcd(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.jobKindCd</code>.
     */
    public String getJobkindcd() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.jobKindNm</code>.
     */
    public void setJobkindnm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.jobKindNm</code>.
     */
    public String getJobkindnm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.userAuth</code>.
     */
    public void setUserauth(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.userAuth</code>.
     */
    public String getUserauth() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.returnCd</code>.
     */
    public void setReturncd(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.returnCd</code>.
     */
    public String getReturncd() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.returnMsg</code>.
     */
    public void setReturnmsg(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.returnMsg</code>.
     */
    public String getReturnmsg() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.failCnt</code>.
     */
    public void setFailcnt(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.failCnt</code>.
     */
    public String getFailcnt() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.dologin.userPw</code>.
     */
    public void setUserpw(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.dologin.userPw</code>.
     */
    public String getUserpw() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Dologin.DOLOGIN.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Dologin.DOLOGIN.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Dologin.DOLOGIN.USERNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Dologin.DOLOGIN.DEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Dologin.DOLOGIN.DEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Dologin.DOLOGIN.JOBKINDCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Dologin.DOLOGIN.JOBKINDNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Dologin.DOLOGIN.USERAUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Dologin.DOLOGIN.RETURNCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Dologin.DOLOGIN.RETURNMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Dologin.DOLOGIN.FAILCNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Dologin.DOLOGIN.USERPW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUsernm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getJobkindcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getJobkindnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUserauth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getReturncd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getReturnmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFailcnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getUserpw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsernm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getJobkindcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getJobkindnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUserauth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getReturncd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getReturnmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFailcnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUserpw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value2(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value3(String value) {
        setUsernm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value4(String value) {
        setDeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value5(String value) {
        setDeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value6(String value) {
        setJobkindcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value7(String value) {
        setJobkindnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value8(String value) {
        setUserauth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value9(String value) {
        setReturncd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value10(String value) {
        setReturnmsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value11(String value) {
        setFailcnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord value12(String value) {
        setUserpw(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DologinRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DologinRecord
     */
    public DologinRecord() {
        super(Dologin.DOLOGIN);
    }

    /**
     * Create a detached, initialised DologinRecord
     */
    public DologinRecord(String hospitalcd, String userid, String usernm, String deptnm, String deptcd, String jobkindcd, String jobkindnm, String userauth, String returncd, String returnmsg, String failcnt, String userpw) {
        super(Dologin.DOLOGIN);

        set(0, hospitalcd);
        set(1, userid);
        set(2, usernm);
        set(3, deptnm);
        set(4, deptcd);
        set(5, jobkindcd);
        set(6, jobkindnm);
        set(7, userauth);
        set(8, returncd);
        set(9, returnmsg);
        set(10, failcnt);
        set(11, userpw);
    }
}
