/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getcodetailhistorylist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * 협진 이력 목록 조회
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetcodetailhistorylistRecord extends TableRecordImpl<GetcodetailhistorylistRecord> implements Record10<String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -745098884;

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.userId</code>.
     */
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.userId</code>.
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.patientId</code>.
     */
    public void setPatientid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.patientId</code>.
     */
    public String getPatientid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.collaborationReqDt</code>.
     */
    public void setCollaborationreqdt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.collaborationReqDt</code>.
     */
    public String getCollaborationreqdt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.doctorId</code>.
     */
    public void setDoctorid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.doctorId</code>.
     */
    public String getDoctorid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.collaborationDeptCd</code>.
     */
    public void setCollaborationdeptcd(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.collaborationDeptCd</code>.
     */
    public String getCollaborationdeptcd() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.collaborationDrId</code>.
     */
    public void setCollaborationdrid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.collaborationDrId</code>.
     */
    public String getCollaborationdrid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.collaborationDeptNm</code>.
     */
    public void setCollaborationdeptnm(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.collaborationDeptNm</code>.
     */
    public String getCollaborationdeptnm() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.getcodetailhistorylist.collaborationDrNm</code>.
     */
    public void setCollaborationdrnm(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcodetailhistorylist.collaborationDrNm</code>.
     */
    public String getCollaborationdrnm() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.PATIENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.COLLABORATIONREQDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.DEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.DOCTORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.COLLABORATIONDEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.COLLABORATIONDRID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.COLLABORATIONDEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Getcodetailhistorylist.GETCODETAILHISTORYLIST.COLLABORATIONDRNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCollaborationreqdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDoctorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCollaborationdeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCollaborationdrid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCollaborationdeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCollaborationdrnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCollaborationreqdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDoctorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCollaborationdeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCollaborationdrid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCollaborationdeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCollaborationdrnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value2(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value3(String value) {
        setPatientid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value4(String value) {
        setCollaborationreqdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value5(String value) {
        setDeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value6(String value) {
        setDoctorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value7(String value) {
        setCollaborationdeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value8(String value) {
        setCollaborationdrid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value9(String value) {
        setCollaborationdeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord value10(String value) {
        setCollaborationdrnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetcodetailhistorylistRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetcodetailhistorylistRecord
     */
    public GetcodetailhistorylistRecord() {
        super(Getcodetailhistorylist.GETCODETAILHISTORYLIST);
    }

    /**
     * Create a detached, initialised GetcodetailhistorylistRecord
     */
    public GetcodetailhistorylistRecord(String hospitalcd, String userid, String patientid, String collaborationreqdt, String deptcd, String doctorid, String collaborationdeptcd, String collaborationdrid, String collaborationdeptnm, String collaborationdrnm) {
        super(Getcodetailhistorylist.GETCODETAILHISTORYLIST);

        set(0, hospitalcd);
        set(1, userid);
        set(2, patientid);
        set(3, collaborationreqdt);
        set(4, deptcd);
        set(5, doctorid);
        set(6, collaborationdeptcd);
        set(7, collaborationdrid);
        set(8, collaborationdeptnm);
        set(9, collaborationdrnm);
    }
}
