/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getcollaborationdetail;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetcollaborationdetailRecord extends TableRecordImpl<GetcollaborationdetailRecord> {

    private static final long serialVersionUID = -2059688069;

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.patientId</code>.
     */
    public void setPatientid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.patientId</code>.
     */
    public String getPatientid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.patientNm</code>.
     */
    public void setPatientnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.patientNm</code>.
     */
    public String getPatientnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.age</code>.
     */
    public void setAge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.age</code>.
     */
    public String getAge() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.wardNm</code>.
     */
    public void setWardnm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.wardNm</code>.
     */
    public String getWardnm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.roomNm</code>.
     */
    public void setRoomnm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.roomNm</code>.
     */
    public String getRoomnm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.bedNm</code>.
     */
    public void setBednm(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.bedNm</code>.
     */
    public String getBednm() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.receiptNo</code>.
     */
    public void setReceiptno(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.receiptNo</code>.
     */
    public String getReceiptno() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.doctorNm</code>.
     */
    public void setDoctornm(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.doctorNm</code>.
     */
    public String getDoctornm() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.doctorTel</code>.
     */
    public void setDoctortel(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.doctorTel</code>.
     */
    public String getDoctortel() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.birthDt</code>.
     */
    public void setBirthdt(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.birthDt</code>.
     */
    public String getBirthdt() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.diagnosisNm</code>.
     */
    public void setDiagnosisnm(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.diagnosisNm</code>.
     */
    public String getDiagnosisnm() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.operationDt</code>.
     */
    public void setOperationdt(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.operationDt</code>.
     */
    public String getOperationdt() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.operationNm</code>.
     */
    public void setOperationnm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.operationNm</code>.
     */
    public String getOperationnm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationDeptNm</code>.
     */
    public void setCollaborationdeptnm(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationDeptNm</code>.
     */
    public String getCollaborationdeptnm() {
        return (String) get(16);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationDrNm</code>.
     */
    public void setCollaborationdrnm(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationDrNm</code>.
     */
    public String getCollaborationdrnm() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationDrTel</code>.
     */
    public void setCollaborationdrtel(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationDrTel</code>.
     */
    public String getCollaborationdrtel() {
        return (String) get(18);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationReqDt</code>.
     */
    public void setCollaborationreqdt(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationReqDt</code>.
     */
    public String getCollaborationreqdt() {
        return (String) get(19);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationReqTxt</code>.
     */
    public void setCollaborationreqtxt(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationReqTxt</code>.
     */
    public String getCollaborationreqtxt() {
        return (String) get(20);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationResDt</code>.
     */
    public void setCollaborationresdt(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationResDt</code>.
     */
    public String getCollaborationresdt() {
        return (String) get(21);
    }

    /**
     * Setter for <code>mplus_test_data.getcollaborationdetail.collaborationResTxt</code>.
     */
    public void setCollaborationrestxt(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcollaborationdetail.collaborationResTxt</code>.
     */
    public String getCollaborationrestxt() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetcollaborationdetailRecord
     */
    public GetcollaborationdetailRecord() {
        super(Getcollaborationdetail.GETCOLLABORATIONDETAIL);
    }

    /**
     * Create a detached, initialised GetcollaborationdetailRecord
     */
    public GetcollaborationdetailRecord(String hospitalcd, String patientid, String patientnm, String age, String gender, String wardnm, String roomnm, String bednm, String receiptno, String deptnm, String doctornm, String doctortel, String birthdt, String diagnosisnm, String operationdt, String operationnm, String collaborationdeptnm, String collaborationdrnm, String collaborationdrtel, String collaborationreqdt, String collaborationreqtxt, String collaborationresdt, String collaborationrestxt) {
        super(Getcollaborationdetail.GETCOLLABORATIONDETAIL);

        set(0, hospitalcd);
        set(1, patientid);
        set(2, patientnm);
        set(3, age);
        set(4, gender);
        set(5, wardnm);
        set(6, roomnm);
        set(7, bednm);
        set(8, receiptno);
        set(9, deptnm);
        set(10, doctornm);
        set(11, doctortel);
        set(12, birthdt);
        set(13, diagnosisnm);
        set(14, operationdt);
        set(15, operationnm);
        set(16, collaborationdeptnm);
        set(17, collaborationdrnm);
        set(18, collaborationdrtel);
        set(19, collaborationreqdt);
        set(20, collaborationreqtxt);
        set(21, collaborationresdt);
        set(22, collaborationrestxt);
    }
}
