/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getcopatientlist;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetcopatientlistRecord extends TableRecordImpl<GetcopatientlistRecord> {

    private static final long serialVersionUID = 2143673078;

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.patientId</code>.
     */
    public void setPatientid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.patientId</code>.
     */
    public String getPatientid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.patientNm</code>.
     */
    public void setPatientnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.patientNm</code>.
     */
    public String getPatientnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.age</code>.
     */
    public void setAge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.age</code>.
     */
    public String getAge() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.wardNm</code>.
     */
    public void setWardnm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.wardNm</code>.
     */
    public String getWardnm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.roomNm</code>.
     */
    public void setRoomnm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.roomNm</code>.
     */
    public String getRoomnm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.bedNm</code>.
     */
    public void setBednm(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.bedNm</code>.
     */
    public String getBednm() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.receiptNo</code>.
     */
    public void setReceiptno(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.receiptNo</code>.
     */
    public String getReceiptno() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.doctorNm</code>.
     */
    public void setDoctornm(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.doctorNm</code>.
     */
    public String getDoctornm() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.doctorId</code>.
     */
    public void setDoctorid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.doctorId</code>.
     */
    public String getDoctorid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.birthDt</code>.
     */
    public void setBirthdt(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.birthDt</code>.
     */
    public String getBirthdt() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationDeptCd</code>.
     */
    public void setCollaborationdeptcd(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationDeptCd</code>.
     */
    public String getCollaborationdeptcd() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationDeptNm</code>.
     */
    public void setCollaborationdeptnm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationDeptNm</code>.
     */
    public String getCollaborationdeptnm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationDrId</code>.
     */
    public void setCollaborationdrid(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationDrId</code>.
     */
    public String getCollaborationdrid() {
        return (String) get(16);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationDrNm</code>.
     */
    public void setCollaborationdrnm(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationDrNm</code>.
     */
    public String getCollaborationdrnm() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationReqDt</code>.
     */
    public void setCollaborationreqdt(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationReqDt</code>.
     */
    public String getCollaborationreqdt() {
        return (String) get(18);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationResDt</code>.
     */
    public void setCollaborationresdt(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationResDt</code>.
     */
    public String getCollaborationresdt() {
        return (String) get(19);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.collaborationStatNm</code>.
     */
    public void setCollaborationstatnm(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.collaborationStatNm</code>.
     */
    public String getCollaborationstatnm() {
        return (String) get(20);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.hospitalizationDt</code>.
     */
    public void setHospitalizationdt(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.hospitalizationDt</code>.
     */
    public String getHospitalizationdt() {
        return (String) get(21);
    }

    /**
     * Setter for <code>mplus_test_data.getcopatientlist.treatCls</code>.
     */
    public void setTreatcls(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>mplus_test_data.getcopatientlist.treatCls</code>.
     */
    public String getTreatcls() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetcopatientlistRecord
     */
    public GetcopatientlistRecord() {
        super(Getcopatientlist.GETCOPATIENTLIST);
    }

    /**
     * Create a detached, initialised GetcopatientlistRecord
     */
    public GetcopatientlistRecord(String hospitalcd, String patientid, String patientnm, String age, String gender, String wardnm, String roomnm, String bednm, String receiptno, String deptcd, String deptnm, String doctornm, String doctorid, String birthdt, String collaborationdeptcd, String collaborationdeptnm, String collaborationdrid, String collaborationdrnm, String collaborationreqdt, String collaborationresdt, String collaborationstatnm, String hospitalizationdt, String treatcls) {
        super(Getcopatientlist.GETCOPATIENTLIST);

        set(0, hospitalcd);
        set(1, patientid);
        set(2, patientnm);
        set(3, age);
        set(4, gender);
        set(5, wardnm);
        set(6, roomnm);
        set(7, bednm);
        set(8, receiptno);
        set(9, deptcd);
        set(10, deptnm);
        set(11, doctornm);
        set(12, doctorid);
        set(13, birthdt);
        set(14, collaborationdeptcd);
        set(15, collaborationdeptnm);
        set(16, collaborationdrid);
        set(17, collaborationdrnm);
        set(18, collaborationreqdt);
        set(19, collaborationresdt);
        set(20, collaborationstatnm);
        set(21, hospitalizationdt);
        set(22, treatcls);
    }
}
