/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getdoctorinfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetdoctorinfoRecord extends TableRecordImpl<GetdoctorinfoRecord> implements Record7<String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1548109466;

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.doctorId</code>.
     */
    public void setDoctorid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.doctorId</code>.
     */
    public String getDoctorid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.doctorNm</code>.
     */
    public void setDoctornm(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.doctorNm</code>.
     */
    public String getDoctornm() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.doctorTel</code>.
     */
    public void setDoctortel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.doctorTel</code>.
     */
    public String getDoctortel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getdoctorinfo.speciality</code>.
     */
    public void setSpeciality(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getdoctorinfo.speciality</code>.
     */
    public String getSpeciality() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getdoctorinfo.GETDOCTORINFO.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getdoctorinfo.GETDOCTORINFO.DEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getdoctorinfo.GETDOCTORINFO.DEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getdoctorinfo.GETDOCTORINFO.DOCTORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getdoctorinfo.GETDOCTORINFO.DOCTORNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getdoctorinfo.GETDOCTORINFO.DOCTORTEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Getdoctorinfo.GETDOCTORINFO.SPECIALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDoctorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDoctornm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDoctortel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSpeciality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDoctorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDoctornm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDoctortel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSpeciality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value2(String value) {
        setDeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value3(String value) {
        setDeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value4(String value) {
        setDoctorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value5(String value) {
        setDoctornm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value6(String value) {
        setDoctortel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord value7(String value) {
        setSpeciality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetdoctorinfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetdoctorinfoRecord
     */
    public GetdoctorinfoRecord() {
        super(Getdoctorinfo.GETDOCTORINFO);
    }

    /**
     * Create a detached, initialised GetdoctorinfoRecord
     */
    public GetdoctorinfoRecord(String hospitalcd, String deptcd, String deptnm, String doctorid, String doctornm, String doctortel, String speciality) {
        super(Getdoctorinfo.GETDOCTORINFO);

        set(0, hospitalcd);
        set(1, deptcd);
        set(2, deptnm);
        set(3, doctorid);
        set(4, doctornm);
        set(5, doctortel);
        set(6, speciality);
    }
}
