/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getemtreatstatlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetemtreatstatlistRecord extends TableRecordImpl<GetemtreatstatlistRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -749263503;

    /**
     * Setter for <code>mplus_test_data.getemtreatstatlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getemtreatstatlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getemtreatstatlist.emTreatStatCd</code>.
     */
    public void setEmtreatstatcd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getemtreatstatlist.emTreatStatCd</code>.
     */
    public String getEmtreatstatcd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getemtreatstatlist.emTreatStatNm</code>.
     */
    public void setEmtreatstatnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getemtreatstatlist.emTreatStatNm</code>.
     */
    public String getEmtreatstatnm() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getemtreatstatlist.GETEMTREATSTATLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getemtreatstatlist.GETEMTREATSTATLIST.EMTREATSTATCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getemtreatstatlist.GETEMTREATSTATLIST.EMTREATSTATNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEmtreatstatcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmtreatstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmtreatstatcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmtreatstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetemtreatstatlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetemtreatstatlistRecord value2(String value) {
        setEmtreatstatcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetemtreatstatlistRecord value3(String value) {
        setEmtreatstatnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetemtreatstatlistRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetemtreatstatlistRecord
     */
    public GetemtreatstatlistRecord() {
        super(Getemtreatstatlist.GETEMTREATSTATLIST);
    }

    /**
     * Create a detached, initialised GetemtreatstatlistRecord
     */
    public GetemtreatstatlistRecord(String hospitalcd, String emtreatstatcd, String emtreatstatnm) {
        super(Getemtreatstatlist.GETEMTREATSTATLIST);

        set(0, hospitalcd);
        set(1, emtreatstatcd);
        set(2, emtreatstatnm);
    }
}
