/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getexamrsltty2;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getexamrsltty2Record extends TableRecordImpl<Getexamrsltty2Record> implements Record7<String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -517543560;

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.examNm</code>.
     */
    public void setExamnm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.examNm</code>.
     */
    public String getExamnm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.examDt</code>.
     */
    public void setExamdt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.examDt</code>.
     */
    public String getExamdt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.examRsltTxt</code>.
     */
    public void setExamrslttxt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.examRsltTxt</code>.
     */
    public String getExamrslttxt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.isPacs</code>.
     */
    public void setIspacs(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.isPacs</code>.
     */
    public String getIspacs() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.pacsAccessTxt</code>.
     */
    public void setPacsaccesstxt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.pacsAccessTxt</code>.
     */
    public String getPacsaccesstxt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getexamrsltty2.pacsKind</code>.
     */
    public void setPacskind(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getexamrsltty2.pacsKind</code>.
     */
    public String getPacskind() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getexamrsltty2.GETEXAMRSLTTY2.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getexamrsltty2.GETEXAMRSLTTY2.EXAMNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getexamrsltty2.GETEXAMRSLTTY2.EXAMDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getexamrsltty2.GETEXAMRSLTTY2.EXAMRSLTTXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getexamrsltty2.GETEXAMRSLTTY2.ISPACS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getexamrsltty2.GETEXAMRSLTTY2.PACSACCESSTXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Getexamrsltty2.GETEXAMRSLTTY2.PACSKIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExamnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExamdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getExamrslttxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIspacs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPacsaccesstxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPacskind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExamnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExamdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getExamrslttxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIspacs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPacsaccesstxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPacskind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value2(String value) {
        setExamnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value3(String value) {
        setExamdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value4(String value) {
        setExamrslttxt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value5(String value) {
        setIspacs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value6(String value) {
        setPacsaccesstxt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record value7(String value) {
        setPacskind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty2Record values(String value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Getexamrsltty2Record
     */
    public Getexamrsltty2Record() {
        super(Getexamrsltty2.GETEXAMRSLTTY2);
    }

    /**
     * Create a detached, initialised Getexamrsltty2Record
     */
    public Getexamrsltty2Record(String hospitalcd, String examnm, String examdt, String examrslttxt, String ispacs, String pacsaccesstxt, String pacskind) {
        super(Getexamrsltty2.GETEXAMRSLTTY2);

        set(0, hospitalcd);
        set(1, examnm);
        set(2, examdt);
        set(3, examrslttxt);
        set(4, ispacs);
        set(5, pacsaccesstxt);
        set(6, pacskind);
    }
}
