/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getmedirecorddetail;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetmedirecorddetailRecord extends TableRecordImpl<GetmedirecorddetailRecord> implements Record1<String> {

    private static final long serialVersionUID = 561344820;

    /**
     * Setter for <code>mplus_test_data.getmedirecorddetail.url</code>.
     */
    public void setUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecorddetail.url</code>.
     */
    public String getUrl() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getmedirecorddetail.GETMEDIRECORDDETAIL.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecorddetailRecord value1(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecorddetailRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetmedirecorddetailRecord
     */
    public GetmedirecorddetailRecord() {
        super(Getmedirecorddetail.GETMEDIRECORDDETAIL);
    }

    /**
     * Create a detached, initialised GetmedirecorddetailRecord
     */
    public GetmedirecorddetailRecord(String url) {
        super(Getmedirecorddetail.GETMEDIRECORDDETAIL);

        set(0, url);
    }
}
