/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getmedirecordlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetmedirecordlistRecord extends TableRecordImpl<GetmedirecordlistRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = 1690692558;

    /**
     * Setter for <code>mplus_test_data.getmedirecordlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecordlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getmedirecordlist.medicalRecordSeq</code>.
     */
    public void setMedicalrecordseq(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecordlist.medicalRecordSeq</code>.
     */
    public String getMedicalrecordseq() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getmedirecordlist.medicalRecordDt</code>.
     */
    public void setMedicalrecorddt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecordlist.medicalRecordDt</code>.
     */
    public String getMedicalrecorddt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getmedirecordlist.medicalRecordFormNm</code>.
     */
    public void setMedicalrecordformnm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecordlist.medicalRecordFormNm</code>.
     */
    public String getMedicalrecordformnm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getmedirecordlist.medicalRecordSubTitle</code>.
     */
    public void setMedicalrecordsubtitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecordlist.medicalRecordSubTitle</code>.
     */
    public String getMedicalrecordsubtitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getmedirecordlist.lastWriter</code>.
     */
    public void setLastwriter(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getmedirecordlist.lastWriter</code>.
     */
    public String getLastwriter() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getmedirecordlist.GETMEDIRECORDLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getmedirecordlist.GETMEDIRECORDLIST.MEDICALRECORDSEQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getmedirecordlist.GETMEDIRECORDLIST.MEDICALRECORDDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getmedirecordlist.GETMEDIRECORDLIST.MEDICALRECORDFORMNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getmedirecordlist.GETMEDIRECORDLIST.MEDICALRECORDSUBTITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getmedirecordlist.GETMEDIRECORDLIST.LASTWRITER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMedicalrecordseq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMedicalrecorddt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMedicalrecordformnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMedicalrecordsubtitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLastwriter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMedicalrecordseq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMedicalrecorddt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMedicalrecordformnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMedicalrecordsubtitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLastwriter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord value2(String value) {
        setMedicalrecordseq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord value3(String value) {
        setMedicalrecorddt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord value4(String value) {
        setMedicalrecordformnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord value5(String value) {
        setMedicalrecordsubtitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord value6(String value) {
        setLastwriter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetmedirecordlistRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetmedirecordlistRecord
     */
    public GetmedirecordlistRecord() {
        super(Getmedirecordlist.GETMEDIRECORDLIST);
    }

    /**
     * Create a detached, initialised GetmedirecordlistRecord
     */
    public GetmedirecordlistRecord(String hospitalcd, String medicalrecordseq, String medicalrecorddt, String medicalrecordformnm, String medicalrecordsubtitle, String lastwriter) {
        super(Getmedirecordlist.GETMEDIRECORDLIST);

        set(0, hospitalcd);
        set(1, medicalrecordseq);
        set(2, medicalrecorddt);
        set(3, medicalrecordformnm);
        set(4, medicalrecordsubtitle);
        set(5, lastwriter);
    }
}
