/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getoutpatientlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetoutpatientlistRecord extends TableRecordImpl<GetoutpatientlistRecord> implements Record19<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -485022661;

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.patientId</code>.
     */
    public void setPatientid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.patientId</code>.
     */
    public String getPatientid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.patientNm</code>.
     */
    public void setPatientnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.patientNm</code>.
     */
    public String getPatientnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.age</code>.
     */
    public void setAge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.age</code>.
     */
    public String getAge() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.wardNm</code>.
     */
    public void setWardnm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.wardNm</code>.
     */
    public String getWardnm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.roomNm</code>.
     */
    public void setRoomnm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.roomNm</code>.
     */
    public String getRoomnm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.bedNm</code>.
     */
    public void setBednm(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.bedNm</code>.
     */
    public String getBednm() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.receiptNo</code>.
     */
    public void setReceiptno(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.receiptNo</code>.
     */
    public String getReceiptno() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.doctorNm</code>.
     */
    public void setDoctornm(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.doctorNm</code>.
     */
    public String getDoctornm() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.doctorId</code>.
     */
    public void setDoctorid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.doctorId</code>.
     */
    public String getDoctorid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.birthDt</code>.
     */
    public void setBirthdt(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.birthDt</code>.
     */
    public String getBirthdt() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.outTreatStatNm</code>.
     */
    public void setOuttreatstatnm(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.outTreatStatNm</code>.
     */
    public String getOuttreatstatnm() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.firstTreatYn</code>.
     */
    public void setFirsttreatyn(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.firstTreatYn</code>.
     */
    public String getFirsttreatyn() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.visitDt</code>.
     */
    public void setVisitdt(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.visitDt</code>.
     */
    public String getVisitdt() {
        return (String) get(16);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.treatTm</code>.
     */
    public void setTreattm(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.treatTm</code>.
     */
    public String getTreattm() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mplus_test_data.getoutpatientlist.treatCls</code>.
     */
    public void setTreatcls(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutpatientlist.treatCls</code>.
     */
    public String getTreatcls() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getoutpatientlist.GETOUTPATIENTLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getoutpatientlist.GETOUTPATIENTLIST.PATIENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getoutpatientlist.GETOUTPATIENTLIST.PATIENTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getoutpatientlist.GETOUTPATIENTLIST.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getoutpatientlist.GETOUTPATIENTLIST.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getoutpatientlist.GETOUTPATIENTLIST.WARDNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Getoutpatientlist.GETOUTPATIENTLIST.ROOMNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Getoutpatientlist.GETOUTPATIENTLIST.BEDNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Getoutpatientlist.GETOUTPATIENTLIST.RECEIPTNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Getoutpatientlist.GETOUTPATIENTLIST.DEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Getoutpatientlist.GETOUTPATIENTLIST.DEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Getoutpatientlist.GETOUTPATIENTLIST.DOCTORNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Getoutpatientlist.GETOUTPATIENTLIST.DOCTORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Getoutpatientlist.GETOUTPATIENTLIST.BIRTHDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Getoutpatientlist.GETOUTPATIENTLIST.OUTTREATSTATNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Getoutpatientlist.GETOUTPATIENTLIST.FIRSTTREATYN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Getoutpatientlist.GETOUTPATIENTLIST.VISITDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Getoutpatientlist.GETOUTPATIENTLIST.TREATTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Getoutpatientlist.GETOUTPATIENTLIST.TREATCLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPatientnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getWardnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRoomnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBednm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getReceiptno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDoctornm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getDoctorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getBirthdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getOuttreatstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getFirsttreatyn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getVisitdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getTreattm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getTreatcls();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPatientnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWardnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRoomnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBednm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getReceiptno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDoctornm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDoctorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getBirthdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getOuttreatstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getFirsttreatyn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getVisitdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getTreattm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getTreatcls();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value2(String value) {
        setPatientid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value3(String value) {
        setPatientnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value4(String value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value5(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value6(String value) {
        setWardnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value7(String value) {
        setRoomnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value8(String value) {
        setBednm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value9(String value) {
        setReceiptno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value10(String value) {
        setDeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value11(String value) {
        setDeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value12(String value) {
        setDoctornm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value13(String value) {
        setDoctorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value14(String value) {
        setBirthdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value15(String value) {
        setOuttreatstatnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value16(String value) {
        setFirsttreatyn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value17(String value) {
        setVisitdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value18(String value) {
        setTreattm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord value19(String value) {
        setTreatcls(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutpatientlistRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetoutpatientlistRecord
     */
    public GetoutpatientlistRecord() {
        super(Getoutpatientlist.GETOUTPATIENTLIST);
    }

    /**
     * Create a detached, initialised GetoutpatientlistRecord
     */
    public GetoutpatientlistRecord(String hospitalcd, String patientid, String patientnm, String age, String gender, String wardnm, String roomnm, String bednm, String receiptno, String deptcd, String deptnm, String doctornm, String doctorid, String birthdt, String outtreatstatnm, String firsttreatyn, String visitdt, String treattm, String treatcls) {
        super(Getoutpatientlist.GETOUTPATIENTLIST);

        set(0, hospitalcd);
        set(1, patientid);
        set(2, patientnm);
        set(3, age);
        set(4, gender);
        set(5, wardnm);
        set(6, roomnm);
        set(7, bednm);
        set(8, receiptno);
        set(9, deptcd);
        set(10, deptnm);
        set(11, doctornm);
        set(12, doctorid);
        set(13, birthdt);
        set(14, outtreatstatnm);
        set(15, firsttreatyn);
        set(16, visitdt);
        set(17, treattm);
        set(18, treatcls);
    }
}
