/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getoperationdetail;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetoperationdetailRecord extends TableRecordImpl<GetoperationdetailRecord> {

    private static final long serialVersionUID = 1214461219;

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.patientId</code>.
     */
    public void setPatientid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.patientId</code>.
     */
    public String getPatientid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.patientNm</code>.
     */
    public void setPatientnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.patientNm</code>.
     */
    public String getPatientnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.age</code>.
     */
    public void setAge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.age</code>.
     */
    public String getAge() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.wardNm</code>.
     */
    public void setWardnm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.wardNm</code>.
     */
    public String getWardnm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.roomNm</code>.
     */
    public void setRoomnm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.roomNm</code>.
     */
    public String getRoomnm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.bedNm</code>.
     */
    public void setBednm(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.bedNm</code>.
     */
    public String getBednm() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.receiptNo</code>.
     */
    public void setReceiptno(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.receiptNo</code>.
     */
    public String getReceiptno() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationDeptNm</code>.
     */
    public void setOperationdeptnm(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationDeptNm</code>.
     */
    public String getOperationdeptnm() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationDrNm</code>.
     */
    public void setOperationdrnm(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationDrNm</code>.
     */
    public String getOperationdrnm() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.birthDt</code>.
     */
    public void setBirthdt(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.birthDt</code>.
     */
    public String getBirthdt() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationSeq</code>.
     */
    public void setOperationseq(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationSeq</code>.
     */
    public String getOperationseq() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationNm</code>.
     */
    public void setOperationnm(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationNm</code>.
     */
    public String getOperationnm() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.diagnosisNm</code>.
     */
    public void setDiagnosisnm(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.diagnosisNm</code>.
     */
    public String getDiagnosisnm() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationStatNm</code>.
     */
    public void setOperationstatnm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationStatNm</code>.
     */
    public String getOperationstatnm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationStartDt</code>.
     */
    public void setOperationstartdt(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationStartDt</code>.
     */
    public String getOperationstartdt() {
        return (String) get(16);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationStartTm</code>.
     */
    public void setOperationstarttm(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationStartTm</code>.
     */
    public String getOperationstarttm() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationEndDt</code>.
     */
    public void setOperationenddt(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationEndDt</code>.
     */
    public String getOperationenddt() {
        return (String) get(18);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationEndTm</code>.
     */
    public void setOperationendtm(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationEndTm</code>.
     */
    public String getOperationendtm() {
        return (String) get(19);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationCntrNm</code>.
     */
    public void setOperationcntrnm(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationCntrNm</code>.
     */
    public String getOperationcntrnm() {
        return (String) get(20);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationRoomNm</code>.
     */
    public void setOperationroomnm(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationRoomNm</code>.
     */
    public String getOperationroomnm() {
        return (String) get(21);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.anesthesiaTy</code>.
     */
    public void setAnesthesiaty(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.anesthesiaTy</code>.
     */
    public String getAnesthesiaty() {
        return (String) get(22);
    }

    /**
     * Setter for <code>mplus_test_data.getoperationdetail.operationRmk</code>.
     */
    public void setOperationrmk(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoperationdetail.operationRmk</code>.
     */
    public String getOperationrmk() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetoperationdetailRecord
     */
    public GetoperationdetailRecord() {
        super(Getoperationdetail.GETOPERATIONDETAIL);
    }

    /**
     * Create a detached, initialised GetoperationdetailRecord
     */
    public GetoperationdetailRecord(String hospitalcd, String patientid, String patientnm, String age, String gender, String wardnm, String roomnm, String bednm, String receiptno, String operationdeptnm, String operationdrnm, String birthdt, String operationseq, String operationnm, String diagnosisnm, String operationstatnm, String operationstartdt, String operationstarttm, String operationenddt, String operationendtm, String operationcntrnm, String operationroomnm, String anesthesiaty, String operationrmk) {
        super(Getoperationdetail.GETOPERATIONDETAIL);

        set(0, hospitalcd);
        set(1, patientid);
        set(2, patientnm);
        set(3, age);
        set(4, gender);
        set(5, wardnm);
        set(6, roomnm);
        set(7, bednm);
        set(8, receiptno);
        set(9, operationdeptnm);
        set(10, operationdrnm);
        set(11, birthdt);
        set(12, operationseq);
        set(13, operationnm);
        set(14, diagnosisnm);
        set(15, operationstatnm);
        set(16, operationstartdt);
        set(17, operationstarttm);
        set(18, operationenddt);
        set(19, operationendtm);
        set(20, operationcntrnm);
        set(21, operationroomnm);
        set(22, anesthesiaty);
        set(23, operationrmk);
    }
}
