/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getoutdatelist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetoutdatelistRecord extends TableRecordImpl<GetoutdatelistRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1280816987;

    /**
     * Setter for <code>mplus_test_data.getoutdatelist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutdatelist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getoutdatelist.visitDt</code>.
     */
    public void setVisitdt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutdatelist.visitDt</code>.
     */
    public String getVisitdt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getoutdatelist.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getoutdatelist.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getoutdatelist.GETOUTDATELIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getoutdatelist.GETOUTDATELIST.VISITDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getoutdatelist.GETOUTDATELIST.DEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getVisitdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVisitdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutdatelistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutdatelistRecord value2(String value) {
        setVisitdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutdatelistRecord value3(String value) {
        setDeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetoutdatelistRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetoutdatelistRecord
     */
    public GetoutdatelistRecord() {
        super(Getoutdatelist.GETOUTDATELIST);
    }

    /**
     * Create a detached, initialised GetoutdatelistRecord
     */
    public GetoutdatelistRecord(String hospitalcd, String visitdt, String deptcd) {
        super(Getoutdatelist.GETOUTDATELIST);

        set(0, hospitalcd);
        set(1, visitdt);
        set(2, deptcd);
    }
}
