/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getouttreatstatlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetouttreatstatlistRecord extends TableRecordImpl<GetouttreatstatlistRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1702885877;

    /**
     * Setter for <code>mplus_test_data.getouttreatstatlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getouttreatstatlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getouttreatstatlist.outTreatStatCd</code>.
     */
    public void setOuttreatstatcd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getouttreatstatlist.outTreatStatCd</code>.
     */
    public String getOuttreatstatcd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getouttreatstatlist.outTreatStatNm</code>.
     */
    public void setOuttreatstatnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getouttreatstatlist.outTreatStatNm</code>.
     */
    public String getOuttreatstatnm() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getouttreatstatlist.GETOUTTREATSTATLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getouttreatstatlist.GETOUTTREATSTATLIST.OUTTREATSTATCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getouttreatstatlist.GETOUTTREATSTATLIST.OUTTREATSTATNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOuttreatstatcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOuttreatstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOuttreatstatcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOuttreatstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetouttreatstatlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetouttreatstatlistRecord value2(String value) {
        setOuttreatstatcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetouttreatstatlistRecord value3(String value) {
        setOuttreatstatnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetouttreatstatlistRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetouttreatstatlistRecord
     */
    public GetouttreatstatlistRecord() {
        super(Getouttreatstatlist.GETOUTTREATSTATLIST);
    }

    /**
     * Create a detached, initialised GetouttreatstatlistRecord
     */
    public GetouttreatstatlistRecord(String hospitalcd, String outtreatstatcd, String outtreatstatnm) {
        super(Getouttreatstatlist.GETOUTTREATSTATLIST);

        set(0, hospitalcd);
        set(1, outtreatstatcd);
        set(2, outtreatstatnm);
    }
}
