/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getophistorylist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetophistorylistRecord extends TableRecordImpl<GetophistorylistRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = -1933553184;

    /**
     * Setter for <code>mplus_test_data.getophistorylist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getophistorylist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getophistorylist.operationDt</code>.
     */
    public void setOperationdt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getophistorylist.operationDt</code>.
     */
    public String getOperationdt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getophistorylist.diagnosisNm</code>.
     */
    public void setDiagnosisnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getophistorylist.diagnosisNm</code>.
     */
    public String getDiagnosisnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getophistorylist.operationNm</code>.
     */
    public void setOperationnm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getophistorylist.operationNm</code>.
     */
    public String getOperationnm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getophistorylist.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getophistorylist.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getophistorylist.operationDrNm</code>.
     */
    public void setOperationdrnm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getophistorylist.operationDrNm</code>.
     */
    public String getOperationdrnm() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getophistorylist.GETOPHISTORYLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getophistorylist.GETOPHISTORYLIST.OPERATIONDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getophistorylist.GETOPHISTORYLIST.DIAGNOSISNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getophistorylist.GETOPHISTORYLIST.OPERATIONNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getophistorylist.GETOPHISTORYLIST.DEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getophistorylist.GETOPHISTORYLIST.OPERATIONDRNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOperationdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDiagnosisnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOperationnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOperationdrnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOperationdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDiagnosisnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOperationnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOperationdrnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord value2(String value) {
        setOperationdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord value3(String value) {
        setDiagnosisnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord value4(String value) {
        setOperationnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord value5(String value) {
        setDeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord value6(String value) {
        setOperationdrnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetophistorylistRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetophistorylistRecord
     */
    public GetophistorylistRecord() {
        super(Getophistorylist.GETOPHISTORYLIST);
    }

    /**
     * Create a detached, initialised GetophistorylistRecord
     */
    public GetophistorylistRecord(String hospitalcd, String operationdt, String diagnosisnm, String operationnm, String deptnm, String operationdrnm) {
        super(Getophistorylist.GETOPHISTORYLIST);

        set(0, hospitalcd);
        set(1, operationdt);
        set(2, diagnosisnm);
        set(3, operationnm);
        set(4, deptnm);
        set(5, operationdrnm);
    }
}
