/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getondutymonthsch;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetondutymonthschRecord extends TableRecordImpl<GetondutymonthschRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 262102004;

    /**
     * Setter for <code>mplus_test_data.getondutymonthsch.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getondutymonthsch.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getondutymonthsch.dutyTxt</code>.
     */
    public void setDutytxt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getondutymonthsch.dutyTxt</code>.
     */
    public String getDutytxt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getondutymonthsch.dayCd</code>.
     */
    public void setDaycd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getondutymonthsch.dayCd</code>.
     */
    public String getDaycd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getondutymonthsch.dutyDt</code>.
     */
    public void setDutydt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getondutymonthsch.dutyDt</code>.
     */
    public String getDutydt() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getondutymonthsch.GETONDUTYMONTHSCH.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getondutymonthsch.GETONDUTYMONTHSCH.DUTYTXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getondutymonthsch.GETONDUTYMONTHSCH.DAYCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getondutymonthsch.GETONDUTYMONTHSCH.DUTYDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDutytxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDaycd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDutydt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDutytxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDaycd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDutydt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetondutymonthschRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetondutymonthschRecord value2(String value) {
        setDutytxt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetondutymonthschRecord value3(String value) {
        setDaycd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetondutymonthschRecord value4(String value) {
        setDutydt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetondutymonthschRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetondutymonthschRecord
     */
    public GetondutymonthschRecord() {
        super(Getondutymonthsch.GETONDUTYMONTHSCH);
    }

    /**
     * Create a detached, initialised GetondutymonthschRecord
     */
    public GetondutymonthschRecord(String hospitalcd, String dutytxt, String daycd, String dutydt) {
        super(Getondutymonthsch.GETONDUTYMONTHSCH);

        set(0, hospitalcd);
        set(1, dutytxt);
        set(2, daycd);
        set(3, dutydt);
    }
}
