/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getprescriptionstatlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetprescriptionstatlistRecord extends TableRecordImpl<GetprescriptionstatlistRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1459233311;

    /**
     * Setter for <code>mplus_test_data.getprescriptionstatlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getprescriptionstatlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getprescriptionstatlist.prescriptionStatCd</code>.
     */
    public void setPrescriptionstatcd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getprescriptionstatlist.prescriptionStatCd</code>.
     */
    public String getPrescriptionstatcd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getprescriptionstatlist.prescriptionStatNm</code>.
     */
    public void setPrescriptionstatnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getprescriptionstatlist.prescriptionStatNm</code>.
     */
    public String getPrescriptionstatnm() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getprescriptionstatlist.GETPRESCRIPTIONSTATLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getprescriptionstatlist.GETPRESCRIPTIONSTATLIST.PRESCRIPTIONSTATCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getprescriptionstatlist.GETPRESCRIPTIONSTATLIST.PRESCRIPTIONSTATNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPrescriptionstatcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrescriptionstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrescriptionstatcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrescriptionstatnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetprescriptionstatlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetprescriptionstatlistRecord value2(String value) {
        setPrescriptionstatcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetprescriptionstatlistRecord value3(String value) {
        setPrescriptionstatnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetprescriptionstatlistRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetprescriptionstatlistRecord
     */
    public GetprescriptionstatlistRecord() {
        super(Getprescriptionstatlist.GETPRESCRIPTIONSTATLIST);
    }

    /**
     * Create a detached, initialised GetprescriptionstatlistRecord
     */
    public GetprescriptionstatlistRecord(String hospitalcd, String prescriptionstatcd, String prescriptionstatnm) {
        super(Getprescriptionstatlist.GETPRESCRIPTIONSTATLIST);

        set(0, hospitalcd);
        set(1, prescriptionstatcd);
        set(2, prescriptionstatnm);
    }
}
