/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getpatientinfo;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetpatientinfoRecord extends TableRecordImpl<GetpatientinfoRecord> {

    private static final long serialVersionUID = 1949222725;

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.patientId</code>.
     */
    public void setPatientid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.patientId</code>.
     */
    public String getPatientid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.patientNm</code>.
     */
    public void setPatientnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.patientNm</code>.
     */
    public String getPatientnm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.age</code>.
     */
    public void setAge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.age</code>.
     */
    public String getAge() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.wardNm</code>.
     */
    public void setWardnm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.wardNm</code>.
     */
    public String getWardnm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.roomNm</code>.
     */
    public void setRoomnm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.roomNm</code>.
     */
    public String getRoomnm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.bedNm</code>.
     */
    public void setBednm(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.bedNm</code>.
     */
    public String getBednm() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.receiptNo</code>.
     */
    public void setReceiptno(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.receiptNo</code>.
     */
    public String getReceiptno() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.doctorNm</code>.
     */
    public void setDoctornm(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.doctorNm</code>.
     */
    public String getDoctornm() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.doctorId</code>.
     */
    public void setDoctorid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.doctorId</code>.
     */
    public String getDoctorid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.birthDt</code>.
     */
    public void setBirthdt(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.birthDt</code>.
     */
    public String getBirthdt() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.specialistId</code>.
     */
    public void setSpecialistid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.specialistId</code>.
     */
    public String getSpecialistid() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.specialistNm</code>.
     */
    public void setSpecialistnm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.specialistNm</code>.
     */
    public String getSpecialistnm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.diagnosisNm</code>.
     */
    public void setDiagnosisnm(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.diagnosisNm</code>.
     */
    public String getDiagnosisnm() {
        return (String) get(16);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.operationDt</code>.
     */
    public void setOperationdt(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.operationDt</code>.
     */
    public String getOperationdt() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.operationNm</code>.
     */
    public void setOperationnm(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.operationNm</code>.
     */
    public String getOperationnm() {
        return (String) get(18);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.hospitalizationDt</code>.
     */
    public void setHospitalizationdt(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.hospitalizationDt</code>.
     */
    public String getHospitalizationdt() {
        return (String) get(19);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.hospitalizationRsn</code>.
     */
    public void setHospitalizationrsn(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.hospitalizationRsn</code>.
     */
    public String getHospitalizationrsn() {
        return (String) get(20);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.presentDiseaseCond</code>.
     */
    public void setPresentdiseasecond(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.presentDiseaseCond</code>.
     */
    public String getPresentdiseasecond() {
        return (String) get(21);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.isExamResult</code>.
     */
    public void setIsexamresult(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.isExamResult</code>.
     */
    public String getIsexamresult() {
        return (String) get(22);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.isCollaboration</code>.
     */
    public void setIscollaboration(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.isCollaboration</code>.
     */
    public String getIscollaboration() {
        return (String) get(23);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.isOperation</code>.
     */
    public void setIsoperation(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.isOperation</code>.
     */
    public String getIsoperation() {
        return (String) get(24);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.isTreatment</code>.
     */
    public void setIstreatment(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.isTreatment</code>.
     */
    public String getIstreatment() {
        return (String) get(25);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.cellphoneNo</code>.
     */
    public void setCellphoneno(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.cellphoneNo</code>.
     */
    public String getCellphoneno() {
        return (String) get(26);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.doctorCellphoneNo</code>.
     */
    public void setDoctorcellphoneno(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.doctorCellphoneNo</code>.
     */
    public String getDoctorcellphoneno() {
        return (String) get(27);
    }

    /**
     * Setter for <code>mplus_test_data.getpatientinfo.specialistCellphoneNo</code>.
     */
    public void setSpecialistcellphoneno(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>mplus_test_data.getpatientinfo.specialistCellphoneNo</code>.
     */
    public String getSpecialistcellphoneno() {
        return (String) get(28);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetpatientinfoRecord
     */
    public GetpatientinfoRecord() {
        super(Getpatientinfo.GETPATIENTINFO);
    }

    /**
     * Create a detached, initialised GetpatientinfoRecord
     */
    public GetpatientinfoRecord(String hospitalcd, String patientid, String patientnm, String age, String gender, String wardnm, String roomnm, String bednm, String receiptno, String deptcd, String deptnm, String doctornm, String doctorid, String birthdt, String specialistid, String specialistnm, String diagnosisnm, String operationdt, String operationnm, String hospitalizationdt, String hospitalizationrsn, String presentdiseasecond, String isexamresult, String iscollaboration, String isoperation, String istreatment, String cellphoneno, String doctorcellphoneno, String specialistcellphoneno) {
        super(Getpatientinfo.GETPATIENTINFO);

        set(0, hospitalcd);
        set(1, patientid);
        set(2, patientnm);
        set(3, age);
        set(4, gender);
        set(5, wardnm);
        set(6, roomnm);
        set(7, bednm);
        set(8, receiptno);
        set(9, deptcd);
        set(10, deptnm);
        set(11, doctornm);
        set(12, doctorid);
        set(13, birthdt);
        set(14, specialistid);
        set(15, specialistnm);
        set(16, diagnosisnm);
        set(17, operationdt);
        set(18, operationnm);
        set(19, hospitalizationdt);
        set(20, hospitalizationrsn);
        set(21, presentdiseasecond);
        set(22, isexamresult);
        set(23, iscollaboration);
        set(24, isoperation);
        set(25, istreatment);
        set(26, cellphoneno);
        set(27, doctorcellphoneno);
        set(28, specialistcellphoneno);
    }
}
