/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getshcdeptlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetshcdeptlistRecord extends TableRecordImpl<GetshcdeptlistRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -623492306;

    /**
     * Setter for <code>mplus_test_data.getshcdeptlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getshcdeptlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getshcdeptlist.deptCd</code>.
     */
    public void setDeptcd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getshcdeptlist.deptCd</code>.
     */
    public String getDeptcd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getshcdeptlist.deptNm</code>.
     */
    public void setDeptnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getshcdeptlist.deptNm</code>.
     */
    public String getDeptnm() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getshcdeptlist.GETSHCDEPTLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getshcdeptlist.GETSHCDEPTLIST.DEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getshcdeptlist.GETSHCDEPTLIST.DEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetshcdeptlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetshcdeptlistRecord value2(String value) {
        setDeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetshcdeptlistRecord value3(String value) {
        setDeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetshcdeptlistRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetshcdeptlistRecord
     */
    public GetshcdeptlistRecord() {
        super(Getshcdeptlist.GETSHCDEPTLIST);
    }

    /**
     * Create a detached, initialised GetshcdeptlistRecord
     */
    public GetshcdeptlistRecord(String hospitalcd, String deptcd, String deptnm) {
        super(Getshcdeptlist.GETSHCDEPTLIST);

        set(0, hospitalcd);
        set(1, deptcd);
        set(2, deptnm);
    }
}
