/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getschexamdeptlist;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetschexamdeptlistRecord extends TableRecordImpl<GetschexamdeptlistRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 254684749;

    /**
     * Setter for <code>mplus_test_data.getschexamdeptlist.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getschexamdeptlist.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getschexamdeptlist.examDeptCd</code>.
     */
    public void setExamdeptcd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getschexamdeptlist.examDeptCd</code>.
     */
    public String getExamdeptcd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getschexamdeptlist.examDeptNm</code>.
     */
    public void setExamdeptnm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getschexamdeptlist.examDeptNm</code>.
     */
    public String getExamdeptnm() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getschexamdeptlist.GETSCHEXAMDEPTLIST.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getschexamdeptlist.GETSCHEXAMDEPTLIST.EXAMDEPTCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getschexamdeptlist.GETSCHEXAMDEPTLIST.EXAMDEPTNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExamdeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExamdeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExamdeptcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExamdeptnm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetschexamdeptlistRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetschexamdeptlistRecord value2(String value) {
        setExamdeptcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetschexamdeptlistRecord value3(String value) {
        setExamdeptnm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetschexamdeptlistRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetschexamdeptlistRecord
     */
    public GetschexamdeptlistRecord() {
        super(Getschexamdeptlist.GETSCHEXAMDEPTLIST);
    }

    /**
     * Create a detached, initialised GetschexamdeptlistRecord
     */
    public GetschexamdeptlistRecord(String hospitalcd, String examdeptcd, String examdeptnm) {
        super(Getschexamdeptlist.GETSCHEXAMDEPTLIST);

        set(0, hospitalcd);
        set(1, examdeptcd);
        set(2, examdeptnm);
    }
}
