/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Getvitallistsum2;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getvitallistsum2Record extends TableRecordImpl<Getvitallistsum2Record> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = -1741609472;

    /**
     * Setter for <code>mplus_test_data.getvitallistsum2.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.getvitallistsum2.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.getvitallistsum2.baseDt</code>.
     */
    public void setBasedt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.getvitallistsum2.baseDt</code>.
     */
    public String getBasedt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.getvitallistsum2.item</code>.
     */
    public void setItem(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.getvitallistsum2.item</code>.
     */
    public String getItem() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.getvitallistsum2.total1DayAgo</code>.
     */
    public void setTotal1dayago(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.getvitallistsum2.total1DayAgo</code>.
     */
    public String getTotal1dayago() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.getvitallistsum2.total2DayAgo</code>.
     */
    public void setTotal2dayago(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.getvitallistsum2.total2DayAgo</code>.
     */
    public String getTotal2dayago() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.getvitallistsum2.totalBaseDay</code>.
     */
    public void setTotalbaseday(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.getvitallistsum2.totalBaseDay</code>.
     */
    public String getTotalbaseday() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Getvitallistsum2.GETVITALLISTSUM2.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Getvitallistsum2.GETVITALLISTSUM2.BASEDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Getvitallistsum2.GETVITALLISTSUM2.ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Getvitallistsum2.GETVITALLISTSUM2.TOTAL1DAYAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Getvitallistsum2.GETVITALLISTSUM2.TOTAL2DAYAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Getvitallistsum2.GETVITALLISTSUM2.TOTALBASEDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBasedt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTotal1dayago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTotal2dayago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTotalbaseday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBasedt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTotal1dayago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTotal2dayago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTotalbaseday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record value2(String value) {
        setBasedt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record value3(String value) {
        setItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record value4(String value) {
        setTotal1dayago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record value5(String value) {
        setTotal2dayago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record value6(String value) {
        setTotalbaseday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallistsum2Record values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Getvitallistsum2Record
     */
    public Getvitallistsum2Record() {
        super(Getvitallistsum2.GETVITALLISTSUM2);
    }

    /**
     * Create a detached, initialised Getvitallistsum2Record
     */
    public Getvitallistsum2Record(String hospitalcd, String basedt, String item, String total1dayago, String total2dayago, String totalbaseday) {
        super(Getvitallistsum2.GETVITALLISTSUM2);

        set(0, hospitalcd);
        set(1, basedt);
        set(2, item);
        set(3, total1dayago);
        set(4, total2dayago);
        set(5, totalbaseday);
    }
}
