/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Inputloginlog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InputloginlogRecord extends TableRecordImpl<InputloginlogRecord> implements Record13<String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 427732653;

    /**
     * Setter for <code>mplus_test_data.inputloginlog.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.returnCd</code>.
     */
    public void setReturncd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.returnCd</code>.
     */
    public String getReturncd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.returnMsg</code>.
     */
    public void setReturnmsg(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.returnMsg</code>.
     */
    public String getReturnmsg() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.userId</code>.
     */
    public void setUserid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.userId</code>.
     */
    public String getUserid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.userNm</code>.
     */
    public void setUsernm(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.userNm</code>.
     */
    public String getUsernm() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.deviceId</code>.
     */
    public void setDeviceid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.deviceId</code>.
     */
    public String getDeviceid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.appVersion</code>.
     */
    public void setAppversion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.appVersion</code>.
     */
    public String getAppversion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.appKind</code>.
     */
    public void setAppkind(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.appKind</code>.
     */
    public String getAppkind() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.phoneKind</code>.
     */
    public void setPhonekind(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.phoneKind</code>.
     */
    public String getPhonekind() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.userIp</code>.
     */
    public void setUserip(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.userIp</code>.
     */
    public String getUserip() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.currentDt</code>.
     */
    public void setCurrentdt(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.currentDt</code>.
     */
    public String getCurrentdt() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.successYn</code>.
     */
    public void setSuccessyn(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.successYn</code>.
     */
    public String getSuccessyn() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mplus_test_data.inputloginlog.failMsg</code>.
     */
    public void setFailmsg(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputloginlog.failMsg</code>.
     */
    public String getFailmsg() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Inputloginlog.INPUTLOGINLOG.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Inputloginlog.INPUTLOGINLOG.RETURNCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Inputloginlog.INPUTLOGINLOG.RETURNMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Inputloginlog.INPUTLOGINLOG.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Inputloginlog.INPUTLOGINLOG.USERNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Inputloginlog.INPUTLOGINLOG.DEVICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Inputloginlog.INPUTLOGINLOG.APPVERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Inputloginlog.INPUTLOGINLOG.APPKIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Inputloginlog.INPUTLOGINLOG.PHONEKIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Inputloginlog.INPUTLOGINLOG.USERIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Inputloginlog.INPUTLOGINLOG.CURRENTDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Inputloginlog.INPUTLOGINLOG.SUCCESSYN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Inputloginlog.INPUTLOGINLOG.FAILMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReturncd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReturnmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsernm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAppversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAppkind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPhonekind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUserip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCurrentdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getSuccessyn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFailmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReturncd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReturnmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsernm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAppversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAppkind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPhonekind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUserip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCurrentdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSuccessyn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFailmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value2(String value) {
        setReturncd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value3(String value) {
        setReturnmsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value4(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value5(String value) {
        setUsernm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value6(String value) {
        setDeviceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value7(String value) {
        setAppversion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value8(String value) {
        setAppkind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value9(String value) {
        setPhonekind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value10(String value) {
        setUserip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value11(String value) {
        setCurrentdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value12(String value) {
        setSuccessyn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord value13(String value) {
        setFailmsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputloginlogRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InputloginlogRecord
     */
    public InputloginlogRecord() {
        super(Inputloginlog.INPUTLOGINLOG);
    }

    /**
     * Create a detached, initialised InputloginlogRecord
     */
    public InputloginlogRecord(String hospitalcd, String returncd, String returnmsg, String userid, String usernm, String deviceid, String appversion, String appkind, String phonekind, String userip, String currentdt, String successyn, String failmsg) {
        super(Inputloginlog.INPUTLOGINLOG);

        set(0, hospitalcd);
        set(1, returncd);
        set(2, returnmsg);
        set(3, userid);
        set(4, usernm);
        set(5, deviceid);
        set(6, appversion);
        set(7, appkind);
        set(8, phonekind);
        set(9, userip);
        set(10, currentdt);
        set(11, successyn);
        set(12, failmsg);
    }
}
