/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables.records;


import com.treetory.dsltest.model.tables.Inputdownloadlog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InputdownloadlogRecord extends TableRecordImpl<InputdownloadlogRecord> implements Record10<String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -571500389;

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.hospitalCd</code>.
     */
    public void setHospitalcd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.hospitalCd</code>.
     */
    public String getHospitalcd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.returnCd</code>.
     */
    public void setReturncd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.returnCd</code>.
     */
    public String getReturncd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.returnMsg</code>.
     */
    public void setReturnmsg(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.returnMsg</code>.
     */
    public String getReturnmsg() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.failCnt</code>.
     */
    public void setFailcnt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.failCnt</code>.
     */
    public String getFailcnt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.userId</code>.
     */
    public void setUserid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.userId</code>.
     */
    public String getUserid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.userNm</code>.
     */
    public void setUsernm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.userNm</code>.
     */
    public String getUsernm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.appKind</code>.
     */
    public void setAppkind(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.appKind</code>.
     */
    public String getAppkind() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.appVersion</code>.
     */
    public void setAppversion(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.appVersion</code>.
     */
    public String getAppversion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.userIp</code>.
     */
    public void setUserip(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.userIp</code>.
     */
    public String getUserip() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mplus_test_data.inputdownloadlog.currentDt</code>.
     */
    public void setCurrentdt(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mplus_test_data.inputdownloadlog.currentDt</code>.
     */
    public String getCurrentdt() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.HOSPITALCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.RETURNCD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.RETURNMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.FAILCNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.USERNM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.APPKIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.APPVERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.USERIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Inputdownloadlog.INPUTDOWNLOADLOG.CURRENTDT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReturncd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReturnmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFailcnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUsernm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAppkind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAppversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUserip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCurrentdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHospitalcd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReturncd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReturnmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFailcnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsernm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAppkind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAppversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUserip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCurrentdt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value1(String value) {
        setHospitalcd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value2(String value) {
        setReturncd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value3(String value) {
        setReturnmsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value4(String value) {
        setFailcnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value5(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value6(String value) {
        setUsernm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value7(String value) {
        setAppkind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value8(String value) {
        setAppversion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value9(String value) {
        setUserip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord value10(String value) {
        setCurrentdt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InputdownloadlogRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InputdownloadlogRecord
     */
    public InputdownloadlogRecord() {
        super(Inputdownloadlog.INPUTDOWNLOADLOG);
    }

    /**
     * Create a detached, initialised InputdownloadlogRecord
     */
    public InputdownloadlogRecord(String hospitalcd, String returncd, String returnmsg, String failcnt, String userid, String usernm, String appkind, String appversion, String userip, String currentdt) {
        super(Inputdownloadlog.INPUTDOWNLOADLOG);

        set(0, hospitalcd);
        set(1, returncd);
        set(2, returnmsg);
        set(3, failcnt);
        set(4, userid);
        set(5, usernm);
        set(6, appkind);
        set(7, appversion);
        set(8, userip);
        set(9, currentdt);
    }
}
