/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetcopatientlistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getcopatientlist extends TableImpl<GetcopatientlistRecord> {

    private static final long serialVersionUID = -764826137;

    /**
     * The reference instance of <code>mplus_test_data.getcopatientlist</code>
     */
    public static final Getcopatientlist GETCOPATIENTLIST = new Getcopatientlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetcopatientlistRecord> getRecordType() {
        return GetcopatientlistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getcopatientlist.hospitalCd</code>.
     */
    public final TableField<GetcopatientlistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.patientId</code>.
     */
    public final TableField<GetcopatientlistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.patientNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> PATIENTNM = createField("patientNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.age</code>.
     */
    public final TableField<GetcopatientlistRecord, String> AGE = createField("age", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.gender</code>.
     */
    public final TableField<GetcopatientlistRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.wardNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> WARDNM = createField("wardNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.roomNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> ROOMNM = createField("roomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.bedNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> BEDNM = createField("bedNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.receiptNo</code>.
     */
    public final TableField<GetcopatientlistRecord, String> RECEIPTNO = createField("receiptNo", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.deptCd</code>.
     */
    public final TableField<GetcopatientlistRecord, String> DEPTCD = createField("deptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.deptNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> DEPTNM = createField("deptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.doctorNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> DOCTORNM = createField("doctorNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.doctorId</code>.
     */
    public final TableField<GetcopatientlistRecord, String> DOCTORID = createField("doctorId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.birthDt</code>.
     */
    public final TableField<GetcopatientlistRecord, String> BIRTHDT = createField("birthDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationDeptCd</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONDEPTCD = createField("collaborationDeptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationDeptNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONDEPTNM = createField("collaborationDeptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationDrId</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONDRID = createField("collaborationDrId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationDrNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONDRNM = createField("collaborationDrNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationReqDt</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONREQDT = createField("collaborationReqDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationResDt</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONRESDT = createField("collaborationResDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.collaborationStatNm</code>.
     */
    public final TableField<GetcopatientlistRecord, String> COLLABORATIONSTATNM = createField("collaborationStatNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.hospitalizationDt</code>.
     */
    public final TableField<GetcopatientlistRecord, String> HOSPITALIZATIONDT = createField("hospitalizationDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcopatientlist.treatCls</code>.
     */
    public final TableField<GetcopatientlistRecord, String> TREATCLS = createField("treatCls", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getcopatientlist</code> table reference
     */
    public Getcopatientlist() {
        this(DSL.name("getcopatientlist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getcopatientlist</code> table reference
     */
    public Getcopatientlist(String alias) {
        this(DSL.name(alias), GETCOPATIENTLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getcopatientlist</code> table reference
     */
    public Getcopatientlist(Name alias) {
        this(alias, GETCOPATIENTLIST);
    }

    private Getcopatientlist(Name alias, Table<GetcopatientlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getcopatientlist(Name alias, Table<GetcopatientlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getcopatientlist(Table<O> child, ForeignKey<O, GetcopatientlistRecord> key) {
        super(child, key, GETCOPATIENTLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getcopatientlist as(String alias) {
        return new Getcopatientlist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getcopatientlist as(Name alias) {
        return new Getcopatientlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getcopatientlist rename(String name) {
        return new Getcopatientlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getcopatientlist rename(Name name) {
        return new Getcopatientlist(name, null);
    }
}
