/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetcodetailhistorylistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 협진 이력 목록 조회
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getcodetailhistorylist extends TableImpl<GetcodetailhistorylistRecord> {

    private static final long serialVersionUID = -1774290373;

    /**
     * The reference instance of <code>mplus_test_data.getcodetailhistorylist</code>
     */
    public static final Getcodetailhistorylist GETCODETAILHISTORYLIST = new Getcodetailhistorylist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetcodetailhistorylistRecord> getRecordType() {
        return GetcodetailhistorylistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.hospitalCd</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.userId</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> USERID = createField("userId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.patientId</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.collaborationReqDt</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> COLLABORATIONREQDT = createField("collaborationReqDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.deptCd</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> DEPTCD = createField("deptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.doctorId</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> DOCTORID = createField("doctorId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.collaborationDeptCd</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> COLLABORATIONDEPTCD = createField("collaborationDeptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.collaborationDrId</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> COLLABORATIONDRID = createField("collaborationDrId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.collaborationDeptNm</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> COLLABORATIONDEPTNM = createField("collaborationDeptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getcodetailhistorylist.collaborationDrNm</code>.
     */
    public final TableField<GetcodetailhistorylistRecord, String> COLLABORATIONDRNM = createField("collaborationDrNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getcodetailhistorylist</code> table reference
     */
    public Getcodetailhistorylist() {
        this(DSL.name("getcodetailhistorylist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getcodetailhistorylist</code> table reference
     */
    public Getcodetailhistorylist(String alias) {
        this(DSL.name(alias), GETCODETAILHISTORYLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getcodetailhistorylist</code> table reference
     */
    public Getcodetailhistorylist(Name alias) {
        this(alias, GETCODETAILHISTORYLIST);
    }

    private Getcodetailhistorylist(Name alias, Table<GetcodetailhistorylistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getcodetailhistorylist(Name alias, Table<GetcodetailhistorylistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("협진 이력 목록 조회"));
    }

    public <O extends Record> Getcodetailhistorylist(Table<O> child, ForeignKey<O, GetcodetailhistorylistRecord> key) {
        super(child, key, GETCODETAILHISTORYLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getcodetailhistorylist as(String alias) {
        return new Getcodetailhistorylist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getcodetailhistorylist as(Name alias) {
        return new Getcodetailhistorylist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getcodetailhistorylist rename(String name) {
        return new Getcodetailhistorylist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getcodetailhistorylist rename(Name name) {
        return new Getcodetailhistorylist(name, null);
    }
}
