/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.Getexamrsltty1Record;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getexamrsltty1 extends TableImpl<Getexamrsltty1Record> {

    private static final long serialVersionUID = -65262713;

    /**
     * The reference instance of <code>mplus_test_data.getexamrsltty1</code>
     */
    public static final Getexamrsltty1 GETEXAMRSLTTY1 = new Getexamrsltty1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Getexamrsltty1Record> getRecordType() {
        return Getexamrsltty1Record.class;
    }

    /**
     * The column <code>mplus_test_data.getexamrsltty1.hospitalCd</code>.
     */
    public final TableField<Getexamrsltty1Record, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.examNm</code>.
     */
    public final TableField<Getexamrsltty1Record, String> EXAMNM = createField("examNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.examDt</code>.
     */
    public final TableField<Getexamrsltty1Record, String> EXAMDT = createField("examDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.specimenNm</code>.
     */
    public final TableField<Getexamrsltty1Record, String> SPECIMENNM = createField("specimenNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.specimenExamNm</code>.
     */
    public final TableField<Getexamrsltty1Record, String> SPECIMENEXAMNM = createField("specimenExamNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.examRsltVal</code>.
     */
    public final TableField<Getexamrsltty1Record, String> EXAMRSLTVAL = createField("examRsltVal", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.referenceVal</code>.
     */
    public final TableField<Getexamrsltty1Record, String> REFERENCEVAL = createField("referenceVal", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.examRsltUnit</code>.
     */
    public final TableField<Getexamrsltty1Record, String> EXAMRSLTUNIT = createField("examRsltUnit", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.judgment</code>.
     */
    public final TableField<Getexamrsltty1Record, String> JUDGMENT = createField("judgment", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getexamrsltty1.examStatNm</code>.
     */
    public final TableField<Getexamrsltty1Record, String> EXAMSTATNM = createField("examStatNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getexamrsltty1</code> table reference
     */
    public Getexamrsltty1() {
        this(DSL.name("getexamrsltty1"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getexamrsltty1</code> table reference
     */
    public Getexamrsltty1(String alias) {
        this(DSL.name(alias), GETEXAMRSLTTY1);
    }

    /**
     * Create an aliased <code>mplus_test_data.getexamrsltty1</code> table reference
     */
    public Getexamrsltty1(Name alias) {
        this(alias, GETEXAMRSLTTY1);
    }

    private Getexamrsltty1(Name alias, Table<Getexamrsltty1Record> aliased) {
        this(alias, aliased, null);
    }

    private Getexamrsltty1(Name alias, Table<Getexamrsltty1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getexamrsltty1(Table<O> child, ForeignKey<O, Getexamrsltty1Record> key) {
        super(child, key, GETEXAMRSLTTY1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty1 as(String alias) {
        return new Getexamrsltty1(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getexamrsltty1 as(Name alias) {
        return new Getexamrsltty1(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getexamrsltty1 rename(String name) {
        return new Getexamrsltty1(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getexamrsltty1 rename(Name name) {
        return new Getexamrsltty1(name, null);
    }
}
