/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetindatelistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getindatelist extends TableImpl<GetindatelistRecord> {

    private static final long serialVersionUID = -1726626935;

    /**
     * The reference instance of <code>mplus_test_data.getindatelist</code>
     */
    public static final Getindatelist GETINDATELIST = new Getindatelist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetindatelistRecord> getRecordType() {
        return GetindatelistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getindatelist.hospitalCd</code>.
     */
    public final TableField<GetindatelistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getindatelist.hospitalizationDt</code>.
     */
    public final TableField<GetindatelistRecord, String> HOSPITALIZATIONDT = createField("hospitalizationDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getindatelist.dischargeDt</code>.
     */
    public final TableField<GetindatelistRecord, String> DISCHARGEDT = createField("dischargeDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getindatelist.deptCd</code>.
     */
    public final TableField<GetindatelistRecord, String> DEPTCD = createField("deptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getindatelist</code> table reference
     */
    public Getindatelist() {
        this(DSL.name("getindatelist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getindatelist</code> table reference
     */
    public Getindatelist(String alias) {
        this(DSL.name(alias), GETINDATELIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getindatelist</code> table reference
     */
    public Getindatelist(Name alias) {
        this(alias, GETINDATELIST);
    }

    private Getindatelist(Name alias, Table<GetindatelistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getindatelist(Name alias, Table<GetindatelistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getindatelist(Table<O> child, ForeignKey<O, GetindatelistRecord> key) {
        super(child, key, GETINDATELIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getindatelist as(String alias) {
        return new Getindatelist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getindatelist as(Name alias) {
        return new Getindatelist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getindatelist rename(String name) {
        return new Getindatelist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getindatelist rename(Name name) {
        return new Getindatelist(name, null);
    }
}
