/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetinpatientlistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getinpatientlist extends TableImpl<GetinpatientlistRecord> {

    private static final long serialVersionUID = -381292956;

    /**
     * The reference instance of <code>mplus_test_data.getinpatientlist</code>
     */
    public static final Getinpatientlist GETINPATIENTLIST = new Getinpatientlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetinpatientlistRecord> getRecordType() {
        return GetinpatientlistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getinpatientlist.hospitalCd</code>.
     */
    public final TableField<GetinpatientlistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.patientId</code>.
     */
    public final TableField<GetinpatientlistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.patientNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> PATIENTNM = createField("patientNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.age</code>.
     */
    public final TableField<GetinpatientlistRecord, String> AGE = createField("age", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.gender</code>.
     */
    public final TableField<GetinpatientlistRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.wardNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> WARDNM = createField("wardNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.roomNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> ROOMNM = createField("roomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.bedNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> BEDNM = createField("bedNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.receiptNo</code>.
     */
    public final TableField<GetinpatientlistRecord, String> RECEIPTNO = createField("receiptNo", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.deptCd</code>.
     */
    public final TableField<GetinpatientlistRecord, String> DEPTCD = createField("deptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.deptNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> DEPTNM = createField("deptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.doctorNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> DOCTORNM = createField("doctorNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.doctorId</code>.
     */
    public final TableField<GetinpatientlistRecord, String> DOCTORID = createField("doctorId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.birthDt</code>.
     */
    public final TableField<GetinpatientlistRecord, String> BIRTHDT = createField("birthDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.specialistId</code>.
     */
    public final TableField<GetinpatientlistRecord, String> SPECIALISTID = createField("specialistId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.specialistNm</code>.
     */
    public final TableField<GetinpatientlistRecord, String> SPECIALISTNM = createField("specialistNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.hospitalizationDt</code>.
     */
    public final TableField<GetinpatientlistRecord, String> HOSPITALIZATIONDT = createField("hospitalizationDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.hospitalizationDay</code>.
     */
    public final TableField<GetinpatientlistRecord, String> HOSPITALIZATIONDAY = createField("hospitalizationDay", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getinpatientlist.treatCls</code>.
     */
    public final TableField<GetinpatientlistRecord, String> TREATCLS = createField("treatCls", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getinpatientlist</code> table reference
     */
    public Getinpatientlist() {
        this(DSL.name("getinpatientlist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getinpatientlist</code> table reference
     */
    public Getinpatientlist(String alias) {
        this(DSL.name(alias), GETINPATIENTLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getinpatientlist</code> table reference
     */
    public Getinpatientlist(Name alias) {
        this(alias, GETINPATIENTLIST);
    }

    private Getinpatientlist(Name alias, Table<GetinpatientlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getinpatientlist(Name alias, Table<GetinpatientlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getinpatientlist(Table<O> child, ForeignKey<O, GetinpatientlistRecord> key) {
        super(child, key, GETINPATIENTLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getinpatientlist as(String alias) {
        return new Getinpatientlist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getinpatientlist as(Name alias) {
        return new Getinpatientlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getinpatientlist rename(String name) {
        return new Getinpatientlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getinpatientlist rename(Name name) {
        return new Getinpatientlist(name, null);
    }
}
