/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetoperationcntrlistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getoperationcntrlist extends TableImpl<GetoperationcntrlistRecord> {

    private static final long serialVersionUID = 971665225;

    /**
     * The reference instance of <code>mplus_test_data.getoperationcntrlist</code>
     */
    public static final Getoperationcntrlist GETOPERATIONCNTRLIST = new Getoperationcntrlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetoperationcntrlistRecord> getRecordType() {
        return GetoperationcntrlistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getoperationcntrlist.hospitalCd</code>.
     */
    public final TableField<GetoperationcntrlistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationcntrlist.operationCntrCd</code>.
     */
    public final TableField<GetoperationcntrlistRecord, String> OPERATIONCNTRCD = createField("operationCntrCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationcntrlist.operationCntrNm</code>.
     */
    public final TableField<GetoperationcntrlistRecord, String> OPERATIONCNTRNM = createField("operationCntrNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getoperationcntrlist</code> table reference
     */
    public Getoperationcntrlist() {
        this(DSL.name("getoperationcntrlist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoperationcntrlist</code> table reference
     */
    public Getoperationcntrlist(String alias) {
        this(DSL.name(alias), GETOPERATIONCNTRLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoperationcntrlist</code> table reference
     */
    public Getoperationcntrlist(Name alias) {
        this(alias, GETOPERATIONCNTRLIST);
    }

    private Getoperationcntrlist(Name alias, Table<GetoperationcntrlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getoperationcntrlist(Name alias, Table<GetoperationcntrlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getoperationcntrlist(Table<O> child, ForeignKey<O, GetoperationcntrlistRecord> key) {
        super(child, key, GETOPERATIONCNTRLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoperationcntrlist as(String alias) {
        return new Getoperationcntrlist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoperationcntrlist as(Name alias) {
        return new Getoperationcntrlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoperationcntrlist rename(String name) {
        return new Getoperationcntrlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoperationcntrlist rename(Name name) {
        return new Getoperationcntrlist(name, null);
    }
}
