/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetoperationdetailRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getoperationdetail extends TableImpl<GetoperationdetailRecord> {

    private static final long serialVersionUID = 94073019;

    /**
     * The reference instance of <code>mplus_test_data.getoperationdetail</code>
     */
    public static final Getoperationdetail GETOPERATIONDETAIL = new Getoperationdetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetoperationdetailRecord> getRecordType() {
        return GetoperationdetailRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getoperationdetail.hospitalCd</code>.
     */
    public final TableField<GetoperationdetailRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.patientId</code>.
     */
    public final TableField<GetoperationdetailRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.patientNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> PATIENTNM = createField("patientNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.age</code>.
     */
    public final TableField<GetoperationdetailRecord, String> AGE = createField("age", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.gender</code>.
     */
    public final TableField<GetoperationdetailRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.wardNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> WARDNM = createField("wardNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.roomNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> ROOMNM = createField("roomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.bedNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> BEDNM = createField("bedNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.receiptNo</code>.
     */
    public final TableField<GetoperationdetailRecord, String> RECEIPTNO = createField("receiptNo", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationDeptNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONDEPTNM = createField("operationDeptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationDrNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONDRNM = createField("operationDrNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.birthDt</code>.
     */
    public final TableField<GetoperationdetailRecord, String> BIRTHDT = createField("birthDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationSeq</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONSEQ = createField("operationSeq", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONNM = createField("operationNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.diagnosisNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> DIAGNOSISNM = createField("diagnosisNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationStatNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONSTATNM = createField("operationStatNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationStartDt</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONSTARTDT = createField("operationStartDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationStartTm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONSTARTTM = createField("operationStartTm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationEndDt</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONENDDT = createField("operationEndDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationEndTm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONENDTM = createField("operationEndTm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationCntrNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONCNTRNM = createField("operationCntrNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationRoomNm</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONROOMNM = createField("operationRoomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.anesthesiaTy</code>.
     */
    public final TableField<GetoperationdetailRecord, String> ANESTHESIATY = createField("anesthesiaTy", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoperationdetail.operationRmk</code>.
     */
    public final TableField<GetoperationdetailRecord, String> OPERATIONRMK = createField("operationRmk", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getoperationdetail</code> table reference
     */
    public Getoperationdetail() {
        this(DSL.name("getoperationdetail"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoperationdetail</code> table reference
     */
    public Getoperationdetail(String alias) {
        this(DSL.name(alias), GETOPERATIONDETAIL);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoperationdetail</code> table reference
     */
    public Getoperationdetail(Name alias) {
        this(alias, GETOPERATIONDETAIL);
    }

    private Getoperationdetail(Name alias, Table<GetoperationdetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getoperationdetail(Name alias, Table<GetoperationdetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getoperationdetail(Table<O> child, ForeignKey<O, GetoperationdetailRecord> key) {
        super(child, key, GETOPERATIONDETAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoperationdetail as(String alias) {
        return new Getoperationdetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoperationdetail as(Name alias) {
        return new Getoperationdetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoperationdetail rename(String name) {
        return new Getoperationdetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoperationdetail rename(Name name) {
        return new Getoperationdetail(name, null);
    }
}
