/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetoppatientlistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getoppatientlist extends TableImpl<GetoppatientlistRecord> {

    private static final long serialVersionUID = -1860923476;

    /**
     * The reference instance of <code>mplus_test_data.getoppatientlist</code>
     */
    public static final Getoppatientlist GETOPPATIENTLIST = new Getoppatientlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetoppatientlistRecord> getRecordType() {
        return GetoppatientlistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getoppatientlist.hospitalCd</code>.
     */
    public final TableField<GetoppatientlistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.patientId</code>.
     */
    public final TableField<GetoppatientlistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.patientNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> PATIENTNM = createField("patientNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.age</code>.
     */
    public final TableField<GetoppatientlistRecord, String> AGE = createField("age", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.gender</code>.
     */
    public final TableField<GetoppatientlistRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.wardNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> WARDNM = createField("wardNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.roomNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> ROOMNM = createField("roomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.bedNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> BEDNM = createField("bedNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.receiptNo</code>.
     */
    public final TableField<GetoppatientlistRecord, String> RECEIPTNO = createField("receiptNo", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.deptCd</code>.
     */
    public final TableField<GetoppatientlistRecord, String> DEPTCD = createField("deptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.deptNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> DEPTNM = createField("deptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.doctorNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> DOCTORNM = createField("doctorNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.doctorId</code>.
     */
    public final TableField<GetoppatientlistRecord, String> DOCTORID = createField("doctorId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.birthDt</code>.
     */
    public final TableField<GetoppatientlistRecord, String> BIRTHDT = createField("birthDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.operationDt</code>.
     */
    public final TableField<GetoppatientlistRecord, String> OPERATIONDT = createField("operationDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.operationStatNm</code>.
     */
    public final TableField<GetoppatientlistRecord, String> OPERATIONSTATNM = createField("operationStatNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.anesthesiaTy</code>.
     */
    public final TableField<GetoppatientlistRecord, String> ANESTHESIATY = createField("anesthesiaTy", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoppatientlist.treatCls</code>.
     */
    public final TableField<GetoppatientlistRecord, String> TREATCLS = createField("treatCls", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getoppatientlist</code> table reference
     */
    public Getoppatientlist() {
        this(DSL.name("getoppatientlist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoppatientlist</code> table reference
     */
    public Getoppatientlist(String alias) {
        this(DSL.name(alias), GETOPPATIENTLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoppatientlist</code> table reference
     */
    public Getoppatientlist(Name alias) {
        this(alias, GETOPPATIENTLIST);
    }

    private Getoppatientlist(Name alias, Table<GetoppatientlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getoppatientlist(Name alias, Table<GetoppatientlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getoppatientlist(Table<O> child, ForeignKey<O, GetoppatientlistRecord> key) {
        super(child, key, GETOPPATIENTLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoppatientlist as(String alias) {
        return new Getoppatientlist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoppatientlist as(Name alias) {
        return new Getoppatientlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoppatientlist rename(String name) {
        return new Getoppatientlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoppatientlist rename(Name name) {
        return new Getoppatientlist(name, null);
    }
}
