/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetoutpatientlistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getoutpatientlist extends TableImpl<GetoutpatientlistRecord> {

    private static final long serialVersionUID = 279878775;

    /**
     * The reference instance of <code>mplus_test_data.getoutpatientlist</code>
     */
    public static final Getoutpatientlist GETOUTPATIENTLIST = new Getoutpatientlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetoutpatientlistRecord> getRecordType() {
        return GetoutpatientlistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getoutpatientlist.hospitalCd</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.patientId</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.patientNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> PATIENTNM = createField("patientNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.age</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> AGE = createField("age", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.gender</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.wardNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> WARDNM = createField("wardNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.roomNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> ROOMNM = createField("roomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.bedNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> BEDNM = createField("bedNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.receiptNo</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> RECEIPTNO = createField("receiptNo", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.deptCd</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> DEPTCD = createField("deptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.deptNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> DEPTNM = createField("deptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.doctorNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> DOCTORNM = createField("doctorNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.doctorId</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> DOCTORID = createField("doctorId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.birthDt</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> BIRTHDT = createField("birthDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.outTreatStatNm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> OUTTREATSTATNM = createField("outTreatStatNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.firstTreatYn</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> FIRSTTREATYN = createField("firstTreatYn", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.visitDt</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> VISITDT = createField("visitDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.treatTm</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> TREATTM = createField("treatTm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getoutpatientlist.treatCls</code>.
     */
    public final TableField<GetoutpatientlistRecord, String> TREATCLS = createField("treatCls", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getoutpatientlist</code> table reference
     */
    public Getoutpatientlist() {
        this(DSL.name("getoutpatientlist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoutpatientlist</code> table reference
     */
    public Getoutpatientlist(String alias) {
        this(DSL.name(alias), GETOUTPATIENTLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getoutpatientlist</code> table reference
     */
    public Getoutpatientlist(Name alias) {
        this(alias, GETOUTPATIENTLIST);
    }

    private Getoutpatientlist(Name alias, Table<GetoutpatientlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getoutpatientlist(Name alias, Table<GetoutpatientlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getoutpatientlist(Table<O> child, ForeignKey<O, GetoutpatientlistRecord> key) {
        super(child, key, GETOUTPATIENTLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoutpatientlist as(String alias) {
        return new Getoutpatientlist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getoutpatientlist as(Name alias) {
        return new Getoutpatientlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoutpatientlist rename(String name) {
        return new Getoutpatientlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getoutpatientlist rename(Name name) {
        return new Getoutpatientlist(name, null);
    }
}
