/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetopdetailhistorylistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 수술 이력 목록 조회
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getopdetailhistorylist extends TableImpl<GetopdetailhistorylistRecord> {

    private static final long serialVersionUID = -13398990;

    /**
     * The reference instance of <code>mplus_test_data.getopdetailhistorylist</code>
     */
    public static final Getopdetailhistorylist GETOPDETAILHISTORYLIST = new Getopdetailhistorylist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetopdetailhistorylistRecord> getRecordType() {
        return GetopdetailhistorylistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.hospitalCd</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.userId</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> USERID = createField("userId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.patientId</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationDt</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONDT = createField("operationDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationDeptCd</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONDEPTCD = createField("operationDeptCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationDrId</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONDRID = createField("operationDrId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationCntrCd</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONCNTRCD = createField("operationCntrCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationRoomCd</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONROOMCD = createField("operationRoomCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationDeptNm</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONDEPTNM = createField("operationDeptNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getopdetailhistorylist.operationDrNm</code>.
     */
    public final TableField<GetopdetailhistorylistRecord, String> OPERATIONDRNM = createField("operationDrNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getopdetailhistorylist</code> table reference
     */
    public Getopdetailhistorylist() {
        this(DSL.name("getopdetailhistorylist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getopdetailhistorylist</code> table reference
     */
    public Getopdetailhistorylist(String alias) {
        this(DSL.name(alias), GETOPDETAILHISTORYLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getopdetailhistorylist</code> table reference
     */
    public Getopdetailhistorylist(Name alias) {
        this(alias, GETOPDETAILHISTORYLIST);
    }

    private Getopdetailhistorylist(Name alias, Table<GetopdetailhistorylistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getopdetailhistorylist(Name alias, Table<GetopdetailhistorylistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("수술 이력 목록 조회"));
    }

    public <O extends Record> Getopdetailhistorylist(Table<O> child, ForeignKey<O, GetopdetailhistorylistRecord> key) {
        super(child, key, GETOPDETAILHISTORYLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getopdetailhistorylist as(String alias) {
        return new Getopdetailhistorylist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getopdetailhistorylist as(Name alias) {
        return new Getopdetailhistorylist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getopdetailhistorylist rename(String name) {
        return new Getopdetailhistorylist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getopdetailhistorylist rename(Name name) {
        return new Getopdetailhistorylist(name, null);
    }
}
