/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetroomlistbywardRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getroomlistbyward extends TableImpl<GetroomlistbywardRecord> {

    private static final long serialVersionUID = 705748291;

    /**
     * The reference instance of <code>mplus_test_data.getroomlistbyward</code>
     */
    public static final Getroomlistbyward GETROOMLISTBYWARD = new Getroomlistbyward();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetroomlistbywardRecord> getRecordType() {
        return GetroomlistbywardRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getroomlistbyward.hospitalCd</code>.
     */
    public final TableField<GetroomlistbywardRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getroomlistbyward.roomCd</code>.
     */
    public final TableField<GetroomlistbywardRecord, String> ROOMCD = createField("roomCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getroomlistbyward.roomNm</code>.
     */
    public final TableField<GetroomlistbywardRecord, String> ROOMNM = createField("roomNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getroomlistbyward</code> table reference
     */
    public Getroomlistbyward() {
        this(DSL.name("getroomlistbyward"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getroomlistbyward</code> table reference
     */
    public Getroomlistbyward(String alias) {
        this(DSL.name(alias), GETROOMLISTBYWARD);
    }

    /**
     * Create an aliased <code>mplus_test_data.getroomlistbyward</code> table reference
     */
    public Getroomlistbyward(Name alias) {
        this(alias, GETROOMLISTBYWARD);
    }

    private Getroomlistbyward(Name alias, Table<GetroomlistbywardRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getroomlistbyward(Name alias, Table<GetroomlistbywardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getroomlistbyward(Table<O> child, ForeignKey<O, GetroomlistbywardRecord> key) {
        super(child, key, GETROOMLISTBYWARD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getroomlistbyward as(String alias) {
        return new Getroomlistbyward(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getroomlistbyward as(Name alias) {
        return new Getroomlistbyward(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getroomlistbyward rename(String name) {
        return new Getroomlistbyward(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getroomlistbyward rename(Name name) {
        return new Getroomlistbyward(name, null);
    }
}
