/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetvitallistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getvitallist extends TableImpl<GetvitallistRecord> {

    private static final long serialVersionUID = -1851581168;

    /**
     * The reference instance of <code>mplus_test_data.getvitallist</code>
     */
    public static final Getvitallist GETVITALLIST = new Getvitallist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetvitallistRecord> getRecordType() {
        return GetvitallistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getvitallist.hospitalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.patientId</code>.
     */
    public final TableField<GetvitallistRecord, String> PATIENTID = createField("patientId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.hospitalizationDt</code>.
     */
    public final TableField<GetvitallistRecord, String> HOSPITALIZATIONDT = createField("hospitalizationDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.executionDtTm</code>.
     */
    public final TableField<GetvitallistRecord, String> EXECUTIONDTTM = createField("executionDtTm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.writerIp</code>.
     */
    public final TableField<GetvitallistRecord, String> WRITERIP = createField("writerIp", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.pulse</code>.
     */
    public final TableField<GetvitallistRecord, String> PULSE = createField("pulse", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.pulseEvalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> PULSEEVALCD = createField("pulseEvalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.respiration</code>.
     */
    public final TableField<GetvitallistRecord, String> RESPIRATION = createField("respiration", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.respirationEvalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> RESPIRATIONEVALCD = createField("respirationEvalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.bodyTemperature</code>.
     */
    public final TableField<GetvitallistRecord, String> BODYTEMPERATURE = createField("bodyTemperature", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.bodyTemperatureEvalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> BODYTEMPERATUREEVALCD = createField("bodyTemperatureEvalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.systolicBp</code>.
     */
    public final TableField<GetvitallistRecord, String> SYSTOLICBP = createField("systolicBp", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.systolicBpEvalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> SYSTOLICBPEVALCD = createField("systolicBpEvalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.diastolicBp</code>.
     */
    public final TableField<GetvitallistRecord, String> DIASTOLICBP = createField("diastolicBp", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.diastolicBpEvalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> DIASTOLICBPEVALCD = createField("diastolicBpEvalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.bloodOxySaturation</code>.
     */
    public final TableField<GetvitallistRecord, String> BLOODOXYSATURATION = createField("bloodOxySaturation", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getvitallist.bloodOxySaturationEvalCd</code>.
     */
    public final TableField<GetvitallistRecord, String> BLOODOXYSATURATIONEVALCD = createField("bloodOxySaturationEvalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getvitallist</code> table reference
     */
    public Getvitallist() {
        this(DSL.name("getvitallist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getvitallist</code> table reference
     */
    public Getvitallist(String alias) {
        this(DSL.name(alias), GETVITALLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getvitallist</code> table reference
     */
    public Getvitallist(Name alias) {
        this(alias, GETVITALLIST);
    }

    private Getvitallist(Name alias, Table<GetvitallistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getvitallist(Name alias, Table<GetvitallistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getvitallist(Table<O> child, ForeignKey<O, GetvitallistRecord> key) {
        super(child, key, GETVITALLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallist as(String alias) {
        return new Getvitallist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getvitallist as(Name alias) {
        return new Getvitallist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getvitallist rename(String name) {
        return new Getvitallist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getvitallist rename(Name name) {
        return new Getvitallist(name, null);
    }
}
