/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.GetwardlistRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getwardlist extends TableImpl<GetwardlistRecord> {

    private static final long serialVersionUID = 1049909073;

    /**
     * The reference instance of <code>mplus_test_data.getwardlist</code>
     */
    public static final Getwardlist GETWARDLIST = new Getwardlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetwardlistRecord> getRecordType() {
        return GetwardlistRecord.class;
    }

    /**
     * The column <code>mplus_test_data.getwardlist.hospitalCd</code>.
     */
    public final TableField<GetwardlistRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getwardlist.wardCd</code>.
     */
    public final TableField<GetwardlistRecord, String> WARDCD = createField("wardCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.getwardlist.wardNm</code>.
     */
    public final TableField<GetwardlistRecord, String> WARDNM = createField("wardNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.getwardlist</code> table reference
     */
    public Getwardlist() {
        this(DSL.name("getwardlist"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.getwardlist</code> table reference
     */
    public Getwardlist(String alias) {
        this(DSL.name(alias), GETWARDLIST);
    }

    /**
     * Create an aliased <code>mplus_test_data.getwardlist</code> table reference
     */
    public Getwardlist(Name alias) {
        this(alias, GETWARDLIST);
    }

    private Getwardlist(Name alias, Table<GetwardlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Getwardlist(Name alias, Table<GetwardlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Getwardlist(Table<O> child, ForeignKey<O, GetwardlistRecord> key) {
        super(child, key, GETWARDLIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getwardlist as(String alias) {
        return new Getwardlist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Getwardlist as(Name alias) {
        return new Getwardlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Getwardlist rename(String name) {
        return new Getwardlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Getwardlist rename(Name name) {
        return new Getwardlist(name, null);
    }
}
