/*
 * This file is generated by jOOQ.
 */
package com.treetory.dsltest.model.tables;


import com.treetory.dsltest.model.MplusTestData;
import com.treetory.dsltest.model.tables.records.InputloginlogRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inputloginlog extends TableImpl<InputloginlogRecord> {

    private static final long serialVersionUID = 1373283421;

    /**
     * The reference instance of <code>mplus_test_data.inputloginlog</code>
     */
    public static final Inputloginlog INPUTLOGINLOG = new Inputloginlog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InputloginlogRecord> getRecordType() {
        return InputloginlogRecord.class;
    }

    /**
     * The column <code>mplus_test_data.inputloginlog.hospitalCd</code>.
     */
    public final TableField<InputloginlogRecord, String> HOSPITALCD = createField("hospitalCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.returnCd</code>.
     */
    public final TableField<InputloginlogRecord, String> RETURNCD = createField("returnCd", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.returnMsg</code>.
     */
    public final TableField<InputloginlogRecord, String> RETURNMSG = createField("returnMsg", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.userId</code>.
     */
    public final TableField<InputloginlogRecord, String> USERID = createField("userId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.userNm</code>.
     */
    public final TableField<InputloginlogRecord, String> USERNM = createField("userNm", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.deviceId</code>.
     */
    public final TableField<InputloginlogRecord, String> DEVICEID = createField("deviceId", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.appVersion</code>.
     */
    public final TableField<InputloginlogRecord, String> APPVERSION = createField("appVersion", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.appKind</code>.
     */
    public final TableField<InputloginlogRecord, String> APPKIND = createField("appKind", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.phoneKind</code>.
     */
    public final TableField<InputloginlogRecord, String> PHONEKIND = createField("phoneKind", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.userIp</code>.
     */
    public final TableField<InputloginlogRecord, String> USERIP = createField("userIp", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.currentDt</code>.
     */
    public final TableField<InputloginlogRecord, String> CURRENTDT = createField("currentDt", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.successYn</code>.
     */
    public final TableField<InputloginlogRecord, String> SUCCESSYN = createField("successYn", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mplus_test_data.inputloginlog.failMsg</code>.
     */
    public final TableField<InputloginlogRecord, String> FAILMSG = createField("failMsg", org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>mplus_test_data.inputloginlog</code> table reference
     */
    public Inputloginlog() {
        this(DSL.name("inputloginlog"), null);
    }

    /**
     * Create an aliased <code>mplus_test_data.inputloginlog</code> table reference
     */
    public Inputloginlog(String alias) {
        this(DSL.name(alias), INPUTLOGINLOG);
    }

    /**
     * Create an aliased <code>mplus_test_data.inputloginlog</code> table reference
     */
    public Inputloginlog(Name alias) {
        this(alias, INPUTLOGINLOG);
    }

    private Inputloginlog(Name alias, Table<InputloginlogRecord> aliased) {
        this(alias, aliased, null);
    }

    private Inputloginlog(Name alias, Table<InputloginlogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Inputloginlog(Table<O> child, ForeignKey<O, InputloginlogRecord> key) {
        super(child, key, INPUTLOGINLOG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MplusTestData.MPLUS_TEST_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Inputloginlog as(String alias) {
        return new Inputloginlog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Inputloginlog as(Name alias) {
        return new Inputloginlog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Inputloginlog rename(String name) {
        return new Inputloginlog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Inputloginlog rename(Name name) {
        return new Inputloginlog(name, null);
    }
}
